UPDATE SYSADM.PS_ISA_CP_JUNCTION A
SET 
  A.ISA_CP_PROD_ID = '{2}'
, A.ISA_CP_TRIG_FLAG = '{3}'
, A.ISA_PRODVIEW_FLAG = '{4}'
, A.DT_TIMESTAMP = SYSDATE
WHERE EXISTS (
	SELECT 'X'
	FROM SYSADM.PS_ISA_CP_JUNCTION B
	WHERE A.ISA_SITE_ID = B.ISA_SITE_ID
	  AND A.INV_ITEM_ID = B.INV_ITEM_ID
	  AND B.ISA_SITE_ID = '{0}'
	  AND B.INV_ITEM_ID = '{1}'
	  AND B.ISA_CP_PROD_ID <> '{2}'
)
