UPDATE SYSADM.PS_ISA_CP_JUNCTION
SET 
  ISA_CP_PROD_ID = '{2}'
, ISA_CP_TRIG_FLAG = '{3}'
, ISA_PRODVIEW_FLAG = '{4}'
, DT_TIMESTAMP = SYSDATE
WHERE ISA_SITE_ID = '{0}'
  AND ISA_CP_PROD_ID = '{1}'
