SELECT 
  A.CUST_ID
, A.PLANT
, A.INV_ITEM_ID
, A.EFF_STATUS
, A.ISA_CUSTOMER_CAT
, A.IM_CFFT
, A.INV_STOCK_TYPE
, A.ISA_CUSTOMER_MFG
, A.MFG_ITM_ID
, A.PREFERRED_MFG
, A.REORDER_POINT
, A.QTY_MAXIMUM
, A.REORDER_QTY
, A.UNIT_OF_MEASURE
, A.REPAIR_OPTION_LBL
, A.STANDARD_COST
, A.STD_LEAD
, A.UTILIZ_CD
, A.ISA_NRTE_GL_CODE
, A.ISA_ARTE_GL_CODE
, A.ISA_TRTE_GL_CODE
, A.ISA_NHOT_GL_CODE
, A.ISA_MN_TAX_CODE
, A.ISA_NC_TAX_CODE
, A.ISA_UT_TAX_CODE
, A.PROCESS_INSTANCE
FROM SYSADM.PS_ISA_MB_MATMAST A
WHERE A.CUST_ID = '{0}'
  AND A.PROCESS_INSTANCE = {1}