SELECT DISTINCT 
  A.ISA_SITE_ID
, A.SITE_ITEM_PREFIX AS ITEM_PREFIX
, A.SITE_INDICATOR_FLAG
FROM PS_ISA_ENTERPRISE_XREF A
WHERE A.SITE_INDICATOR_FLAG IN ('A','S')
  AND ISNULL(A.ISA_SITE_ID,'') <> ''
ORDER BY A.SITE_ITEM_PREFIX, A.ISA_SITE_ID
