'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=OraOLEDB.Oracle;Data Source=PROD;User Id=EINTERNET;Password=einternet;")>  _
        Public ReadOnly Property oraCNString() As String
            Get
                Return CType(Me("oraCNString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("server=SQL2012;uid=ItemAddWorker;pwd=sdiadmin;initial catalog={0};")>  _
        Public ReadOnly Property sql2012CNString() As String
            Get
                Return CType(Me("sql2012CNString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("server=DAZZLE;uid=sa;pwd=sdiadmin;initial catalog={0};")>  _
        Public ReadOnly Property sqlDAZZLECNString() As String
            Get
                Return CType(Me("sqlDAZZLECNString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GetSiteProdViewList.sql")>  _
        Public ReadOnly Property qryGetSiteProdViewList() As String
            Get
                Return CType(Me("qryGetSiteProdViewList"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GetCatalogProductView.sql")>  _
        Public ReadOnly Property qryGetCatalogProductViewList() As String
            Get
                Return CType(Me("qryGetCatalogProductViewList"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("server=CPLUS_PROD;uid=sa;pwd=coca-cola;initial catalog=Contentplus;")>  _
        Public ReadOnly Property sqlCPlusCNString() As String
            Get
                Return CType(Me("sqlCPlusCNString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("VERB")>  _
        Public ReadOnly Property appLogLevel() As String
            Get
                Return CType(Me("appLogLevel"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GetCPJunctionItemsForSite.sql")>  _
        Public ReadOnly Property qryGetCPJunctionItemListForSite() As String
            Get
                Return CType(Me("qryGetCPJunctionItemListForSite"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ClassAvailableProductsItemCount.sql")>  _
        Public ReadOnly Property qryGetClassAvailProductItemCount() As String
            Get
                Return CType(Me("qryGetClassAvailProductItemCount"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UpdateCPJunction.sql")>  _
        Public ReadOnly Property qryCPJunctionUpdate() As String
            Get
                Return CType(Me("qryCPJunctionUpdate"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ClassAvailableProductsItemCount_CustItemId.sql")>  _
        Public ReadOnly Property qryGetClassAvailProductItemCount_CustItemId() As String
            Get
                Return CType(Me("qryGetClassAvailProductItemCount_CustItemId"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GetClassAvailableProductItemsForProdView.sql")>  _
        Public ReadOnly Property qryGetClassAvailableProductItemsForProdView() As String
            Get
                Return CType(Me("qryGetClassAvailableProductItemsForProdView"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UpdateCPJunctionViaItemID.sql")>  _
        Public ReadOnly Property qryCPJunctionUpdateViaItemID() As String
            Get
                Return CType(Me("qryCPJunctionUpdateViaItemID"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CheckCPJunctionViaPartNumber.sql")>  _
        Public ReadOnly Property qryCheckCPJunctionViaPartNumber() As String
            Get
                Return CType(Me("qryCheckCPJunctionViaPartNumber"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CreateCPJunction.sql")>  _
        Public ReadOnly Property qryCPJunctionAdd() As String
            Get
                Return CType(Me("qryCPJunctionAdd"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UpdateCPJunctionViaPartNumberIfNotEqual.sql")>  _
        Public ReadOnly Property qryCPJunctionUpdateViaPartNoNotEqual() As String
            Get
                Return CType(Me("qryCPJunctionUpdateViaPartNoNotEqual"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UpdateCPJunctionViaItemIDIfNotEqual.sql")>  _
        Public Property qryCPJunctionUpdateViaItemIDNotEqual() As String
            Get
                Return CType(Me("qryCPJunctionUpdateViaItemIDNotEqual"),String)
            End Get
            Set
                Me("qryCPJunctionUpdateViaItemIDNotEqual") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SDI.CPJunctionSync.My.MySettings
            Get
                Return Global.SDI.CPJunctionSync.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
