SELECT 
  WOSTAT.CUST_ID
, WOSTAT.PLANT 
, WOSTAT.ISA_WORK_ORDER_NO
, WOSTAT.ISA_WO_STATUS
, WOSTAT.PROCESS_FLAG
, WOSTAT.DT_TIMESTAMP
, WOSTAT.ISA_ERROR_RAW
, WOSTAT.ISA_ERROR_MSG_80
FROM SYSADM.PS_ISA_MB_STAT_OUT WOSTAT
WHERE WOSTAT.CUST_ID = '{0}'
  AND WOSTAT.PROCESS_FLAG IN ('N','E')
ORDER BY 
  WOSTAT.CUST_ID
, WOSTAT.PLANT 
, WOSTAT.ISA_WORK_ORDER_NO
