'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace AttachmentsHelpDesk
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="helpDeskTicketFileUploaderSoap", [Namespace]:="http://www.sdi.com/")>  _
    Partial Public Class helpDeskTicketFileUploader
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private soapAuthenticationHeaderValueField As soapAuthenticationHeader
        
        Private soapKeyHeaderValueField As soapKeyHeader
        
        Private uploadFileOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.EmailOpsStaff.My.MySettings.Default.EmailOpsStaff_AttachmentsHelpDesk_helpDeskTicketFileUploader
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property soapAuthenticationHeaderValue() As soapAuthenticationHeader
            Get
                Return Me.soapAuthenticationHeaderValueField
            End Get
            Set
                Me.soapAuthenticationHeaderValueField = value
            End Set
        End Property
        
        Public Property soapKeyHeaderValue() As soapKeyHeader
            Get
                Return Me.soapKeyHeaderValueField
            End Get
            Set
                Me.soapKeyHeaderValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event uploadFileCompleted As uploadFileCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("soapKeyHeaderValue"),  _
         System.Web.Services.Protocols.SoapHeaderAttribute("soapAuthenticationHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sdi.com/uploadFile", RequestNamespace:="http://www.sdi.com/", ResponseNamespace:="http://www.sdi.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function uploadFile(ByVal fnameSourceFullPath As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal f() As Byte) As String
            Dim results() As Object = Me.Invoke("uploadFile", New Object() {fnameSourceFullPath, f})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub uploadFileAsync(ByVal fnameSourceFullPath As String, ByVal f() As Byte)
            Me.uploadFileAsync(fnameSourceFullPath, f, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub uploadFileAsync(ByVal fnameSourceFullPath As String, ByVal f() As Byte, ByVal userState As Object)
            If (Me.uploadFileOperationCompleted Is Nothing) Then
                Me.uploadFileOperationCompleted = AddressOf Me.OnuploadFileOperationCompleted
            End If
            Me.InvokeAsync("uploadFile", New Object() {fnameSourceFullPath, f}, Me.uploadFileOperationCompleted, userState)
        End Sub
        
        Private Sub OnuploadFileOperationCompleted(ByVal arg As Object)
            If (Not (Me.uploadFileCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent uploadFileCompleted(Me, New uploadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sdi.com/"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.sdi.com/", IsNullable:=false)>  _
    Partial Public Class soapKeyHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private userNameField As String
        
        Private loginKeyField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property userName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property loginKey() As String
            Get
                Return Me.loginKeyField
            End Get
            Set
                Me.loginKeyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sdi.com/"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.sdi.com/", IsNullable:=false)>  _
    Partial Public Class soapAuthenticationHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private userNameField As String
        
        Private passwordField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property userName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")>  _
    Public Delegate Sub uploadFileCompletedEventHandler(ByVal sender As Object, ByVal e As uploadFileCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class uploadFileCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
