rem
rem FTP -s:C:\SHIPXML\XMLOut260\DDPutXML.ftp
rem FTP -s:C:\SHIPXML\ShipXMLIn\DDGetXML.ftp
rem
cd C:\SHIPXML\XMLOut260
del \\lenka\NYC.DOE\NYCDOE.XML 
C:\SHIPXML\XMLOut260\ShipXMLOut260.exe /log=verbose /db=PROD
copy C:\SHIPXML\XMLOut260\XMLOUT\DOE*.xml \\lenka\NYC.DOE\NYCDOE.XML
copy C:\SHIPXML\XMLOut260\XMLOUT\DOE*.xml C:\SHIPXML\XMLOut260\XMLOUTProcessed
DEL  C:\SHIPXML\XMLOut260\XMLOUT\DOE*.xml
