'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
'
Namespace loadbalance_dazzle2
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SDI_loadbalance_IOSoap", [Namespace]:="http://www.Insiteonline.com")>  _
    Partial Public Class SDI_loadbalance_IO
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private Stat_Change_Email_CopyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Stat_Change_Email_SendOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Stat_Change_Email_check_dir_existOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.UpdEmailOut.My.MySettings.Default.UpdEmailOut_loadbalance_dazzle2_SDI_loadbalance_IO
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event Stat_Change_Email_CopyCompleted As Stat_Change_Email_CopyCompletedEventHandler
        
        '''<remarks/>
        Public Event Stat_Change_Email_SendCompleted As Stat_Change_Email_SendCompletedEventHandler
        
        '''<remarks/>
        Public Event Stat_Change_Email_check_dir_existCompleted As Stat_Change_Email_check_dir_existCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Insiteonline.com/Stat_Change_Email_Copy", RequestNamespace:="http://www.Insiteonline.com", ResponseNamespace:="http://www.Insiteonline.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Stat_Change_Email_Copy(ByVal filepath As String, ByVal StrMessage As String) As String
            Dim results() As Object = Me.Invoke("Stat_Change_Email_Copy", New Object() {filepath, StrMessage})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginStat_Change_Email_Copy(ByVal filepath As String, ByVal StrMessage As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Stat_Change_Email_Copy", New Object() {filepath, StrMessage}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndStat_Change_Email_Copy(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Stat_Change_Email_CopyAsync(ByVal filepath As String, ByVal StrMessage As String)
            Me.Stat_Change_Email_CopyAsync(filepath, StrMessage, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Stat_Change_Email_CopyAsync(ByVal filepath As String, ByVal StrMessage As String, ByVal userState As Object)
            If (Me.Stat_Change_Email_CopyOperationCompleted Is Nothing) Then
                Me.Stat_Change_Email_CopyOperationCompleted = AddressOf Me.OnStat_Change_Email_CopyOperationCompleted
            End If
            Me.InvokeAsync("Stat_Change_Email_Copy", New Object() {filepath, StrMessage}, Me.Stat_Change_Email_CopyOperationCompleted, userState)
        End Sub
        
        Private Sub OnStat_Change_Email_CopyOperationCompleted(ByVal arg As Object)
            If (Not (Me.Stat_Change_Email_CopyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Stat_Change_Email_CopyCompleted(Me, New Stat_Change_Email_CopyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Insiteonline.com/Stat_Change_Email_Send", RequestNamespace:="http://www.Insiteonline.com", ResponseNamespace:="http://www.Insiteonline.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Stat_Change_Email_Send(ByVal filepath As String) As String
            Dim results() As Object = Me.Invoke("Stat_Change_Email_Send", New Object() {filepath})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginStat_Change_Email_Send(ByVal filepath As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Stat_Change_Email_Send", New Object() {filepath}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndStat_Change_Email_Send(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Stat_Change_Email_SendAsync(ByVal filepath As String)
            Me.Stat_Change_Email_SendAsync(filepath, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Stat_Change_Email_SendAsync(ByVal filepath As String, ByVal userState As Object)
            If (Me.Stat_Change_Email_SendOperationCompleted Is Nothing) Then
                Me.Stat_Change_Email_SendOperationCompleted = AddressOf Me.OnStat_Change_Email_SendOperationCompleted
            End If
            Me.InvokeAsync("Stat_Change_Email_Send", New Object() {filepath}, Me.Stat_Change_Email_SendOperationCompleted, userState)
        End Sub
        
        Private Sub OnStat_Change_Email_SendOperationCompleted(ByVal arg As Object)
            If (Not (Me.Stat_Change_Email_SendCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Stat_Change_Email_SendCompleted(Me, New Stat_Change_Email_SendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Insiteonline.com/Stat_Change_Email_check_dir_exist", RequestNamespace:="http://www.Insiteonline.com", ResponseNamespace:="http://www.Insiteonline.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Stat_Change_Email_check_dir_exist(ByVal rootdir As String) As String
            Dim results() As Object = Me.Invoke("Stat_Change_Email_check_dir_exist", New Object() {rootdir})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginStat_Change_Email_check_dir_exist(ByVal rootdir As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Stat_Change_Email_check_dir_exist", New Object() {rootdir}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndStat_Change_Email_check_dir_exist(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Stat_Change_Email_check_dir_existAsync(ByVal rootdir As String)
            Me.Stat_Change_Email_check_dir_existAsync(rootdir, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Stat_Change_Email_check_dir_existAsync(ByVal rootdir As String, ByVal userState As Object)
            If (Me.Stat_Change_Email_check_dir_existOperationCompleted Is Nothing) Then
                Me.Stat_Change_Email_check_dir_existOperationCompleted = AddressOf Me.OnStat_Change_Email_check_dir_existOperationCompleted
            End If
            Me.InvokeAsync("Stat_Change_Email_check_dir_exist", New Object() {rootdir}, Me.Stat_Change_Email_check_dir_existOperationCompleted, userState)
        End Sub
        
        Private Sub OnStat_Change_Email_check_dir_existOperationCompleted(ByVal arg As Object)
            If (Not (Me.Stat_Change_Email_check_dir_existCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Stat_Change_Email_check_dir_existCompleted(Me, New Stat_Change_Email_check_dir_existCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub Stat_Change_Email_CopyCompletedEventHandler(ByVal sender As Object, ByVal e As Stat_Change_Email_CopyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Stat_Change_Email_CopyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub Stat_Change_Email_SendCompletedEventHandler(ByVal sender As Object, ByVal e As Stat_Change_Email_SendCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Stat_Change_Email_SendCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub Stat_Change_Email_check_dir_existCompletedEventHandler(ByVal sender As Object, ByVal e As Stat_Change_Email_check_dir_existCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Stat_Change_Email_check_dir_existCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
