'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SDI.MOMBrandEAMParentApp.dll")>  _
        Public ReadOnly Property ParentApp() As String
            Get
                Return CType(Me("ParentApp"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SDI.MOMBrandEAMParentApp.MOMBrandEAMParentApp")>  _
        Public ReadOnly Property ParentAppClass() As String
            Get
                Return CType(Me("ParentAppClass"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public ReadOnly Property RCPT_GetBatchSize() As String
            Get
                Return CType(Me("RCPT_GetBatchSize"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public ReadOnly Property RCPT_MaxReq() As String
            Get
                Return CType(Me("RCPT_MaxReq"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MOMBrand_RCPT_HTTP_SOAP_TableColMap.xml")>  _
        Public ReadOnly Property RCPT_HTTP_SOAP_DataMap() As String
            Get
                Return CType(Me("RCPT_HTTP_SOAP_DataMap"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("RCPT_HTTP_SOAP_SelectToSend.sql")>  _
        Public ReadOnly Property RCPT_SelectToSend() As String
            Get
                Return CType(Me("RCPT_SelectToSend"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CUST_ID,PLANT,ISA_WORK_ORDER_NO,ACTIVITY_ID,INV_ITEM_ID,RECEIVER_ID,PO_ID,REQ_ID,"& _ 
            "VENDOR_ID,ISA_CUST_BIN,QTY,PRICE_PO,SERIAL_ID,BUSINESS_UNIT_IN,STORAGE_AREA,STOR"& _ 
            "_LEVEL_1,STOR_LEVEL_2,STOR_LEVEL_3,STOR_LEVEL_4,ISA_EMPLID_30")>  _
        Public ReadOnly Property RCPT_UpdateKeyColumns() As String
            Get
                Return CType(Me("RCPT_UpdateKeyColumns"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MOMBrand_RCPT_HTTP_SOAP_Batch.xml")>  _
        Public ReadOnly Property RCPT_HTTP_SOAP_Batch() As String
            Get
                Return CType(Me("RCPT_HTTP_SOAP_Batch"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MOMBrand_RCPT_HTTP_SOAP_Batch_Item.xml")>  _
        Public ReadOnly Property RCPT_HTTP_SOAP_Batch_Item() As String
            Get
                Return CType(Me("RCPT_HTTP_SOAP_Batch_Item"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("RCPT_HTTP_SOAP_UpdateFromResp.sql")>  _
        Public ReadOnly Property RCPT_UpdateInputTable() As String
            Get
                Return CType(Me("RCPT_UpdateInputTable"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public ReadOnly Property RCPT_ClearErrMsgOnSuccess() As String
            Get
                Return CType(Me("RCPT_ClearErrMsgOnSuccess"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("[Tt]=[Pp][Rr][Oo][Cc]\s[Nn]=[0-9]{0,5}(-[A-Za-z0-9_]*)?\s[Cc]=[0-9]{0,5}")>  _
        Public ReadOnly Property RCPT_CanParseErrMsgSignature() As String
            Get
                Return CType(Me("RCPT_CanParseErrMsgSignature"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\s[Nn]=[0-9]{0,5}(-[A-Za-z0-9_]*)?\s")>  _
        Public ReadOnly Property RCPT_ErrMsgId() As String
            Get
                Return CType(Me("RCPT_ErrMsgId"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("RCPT_HTTP_SOAP_GetErrMsgDesc.sql")>  _
        Public ReadOnly Property RCPT_GetErrMsgDesc() As String
            Get
                Return CType(Me("RCPT_GetErrMsgDesc"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SDI.RCPT_HTTP_SOAP.My.MySettings
            Get
                Return Global.SDI.RCPT_HTTP_SOAP.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
