SELECT 
  ISSRET.CUST_ID
, ISSRET.TRANS_CODE
, ISSRET.ISA_WORK_ORDER_NO 
, ISSRET.ACTIVITY_ID
, ISSRET.SERIAL_ID
, ISSRET.PLANT
, ISSRET.INV_ITEM_ID
, ISSRET.ISA_CUST_BIN
, ISSRET.QTY
, ISSRET.BUSINESS_UNIT_IN
, ISSRET.STORAGE_AREA
, ISSRET.STOR_LEVEL_1
, ISSRET.STOR_LEVEL_2
, ISSRET.STOR_LEVEL_3
, ISSRET.STOR_LEVEL_4
, ISSRET.PROCESS_FLAG
, ISSRET.ISA_EMPLID_30
, ISSRET.ISA_ERROR_RAW
, ISSRET.ISA_ERROR_MSG_80
FROM SYSADM.PS_ISA_MB_ISS_RET ISSRET
WHERE ISSRET.CUST_ID = '{0}'
  AND ISSRET.PROCESS_FLAG IN ('N','E')
ORDER BY 
  ISSRET.TRANS_CODE DESC
, ISSRET.PLANT
, ISSRET.ISA_WORK_ORDER_NO 
, ISSRET.ACTIVITY_ID
, ISSRET.INV_ITEM_ID
, ISSRET.ISA_CUST_BIN
