UPDATE SYSADM.PS_ISA_LOAD_INT LD1
SET 
  LD1.ISA_LOAD_STATUS = 'E'
, LD1.BNK_LOAD_DTTM = SYSDATE
WHERE EXISTS (
    SELECT 'X'
    FROM 
      SYSADM.PS_ISA_LOAD_INT LD2
    , SYSADM.PS_ISA_SHIPTO_LOAD SHP2
    WHERE LD2.LOAD_ID = LD1.LOAD_ID
      AND LD2.SHIPTO_ID = LD1.SHIPTO_ID
      AND LD2.ORDER_NO = LD1.ORDER_NO
      AND LD2.SHIP_CNTR_ID = LD1.SHIP_CNTR_ID
      AND LD2.SHIPTO_ID_RESP = LD1.SHIPTO_ID_RESP
      AND LD2.ISA_LANE_ID = LD1.ISA_LANE_ID
      AND LD2.ISA_STOP_NBR = LD1.ISA_STOP_NBR
      AND LD2.CONTAINER_TYPE = LD1.CONTAINER_TYPE
      AND LD2.ENTRY_TYPE = LD1.ENTRY_TYPE
      AND LD2.ISA_TRUCK_ID = LD1.ISA_TRUCK_ID
      AND LD2.SHIPTO_ID = SHP2.SHIPTO_ID
      AND LD2.ISA_LOAD_STATUS IN ('L')
      AND SHP2.BUSINESS_UNIT_OM = '{0}'
)
