SELECT 
  XSTOR.CUST_ID
, XSTOR.PLANT
, XSTOR.INV_ITEM_ID
, XSTOR.ISA_CUST_BIN
, XSTOR.QTY
, XSTOR.ISA_TO_PLANT
, XSTOR.SERIAL_ID 
, XSTOR.ISA_CUST_TO_BIN
, XSTOR.BUSINESS_UNIT_IN
, XSTOR.STORAGE_AREA
, XSTOR.STOR_LEVEL_1
, XSTOR.STOR_LEVEL_2
, XSTOR.STOR_LEVEL_3
, XSTOR.STOR_LEVEL_4
, XSTOR.TO_BU
, XSTOR.TO_STOR_AREA
, XSTOR.TO_STOR_LEVEL_1
, XSTOR.TO_STOR_LEVEL_2
, XSTOR.TO_STOR_LEVEL_3
, XSTOR.TO_STOR_LEVEL_4
, XSTOR.PROCESS_FLAG
, XSTOR.ISA_ERROR_RAW
, XSTOR.ISA_ERROR_MSG_80
FROM SYSADM.PS_ISA_MB_IBU_XFER XSTOR
WHERE XSTOR.CUST_ID = '{0}'
  AND XSTOR.PROCESS_FLAG IN ('N','E')
ORDER BY 
  XSTOR.ISA_TO_PLANT
, XSTOR.INV_ITEM_ID
, XSTOR.ISA_CUST_TO_BIN
