SELECT 
  XBIN.CUST_ID 
, XBIN.PLANT 
, XBIN.INV_ITEM_ID 
, XBIN.ISA_CUST_BIN 
, XBIN.QTY 
, XBIN.ISA_CUST_TO_BIN 
, XBIN.BUSINESS_UNIT_IN 
, XBIN.STORAGE_AREA 
, XBIN.STOR_LEVEL_1 
, XBIN.STOR_LEVEL_2 
, XBIN.STOR_LEVEL_3 
, XBIN.STOR_LEVEL_4 
, XBIN.TO_STOR_AREA 
, XBIN.TO_STOR_LEVEL_1 
, XBIN.TO_STOR_LEVEL_2 
, XBIN.TO_STOR_LEVEL_3 
, XBIN.TO_STOR_LEVEL_4 
, XBIN.SERIAL_ID 
, XBIN.PROCESS_FLAG
FROM SYSADM.PS_ISA_MB_BIN_XFER XBIN
WHERE XBIN.CUST_ID = '{0}'
  AND XBIN.PROCESS_FLAG IN ('N','E')
ORDER BY 
  XBIN.PLANT 
, XBIN.INV_ITEM_ID 
, XBIN.ISA_CUST_TO_BIN 
