rem
rem FTP -s:C:\SHIPXML\XMLOut260FAB\DDPutXML.ftp
rem FTP -s:C:\SHIPXML\ShipXMLIn\DDGetXML.ftp
rem
cd C:\SHIPXML\XMLOut260FAB\XMLOUT
rem del \\lenka\NYC.DOE\NYCDELIVFAB.txt
del \\lenka\c$\Inetpub\NYC.DOE\NYCDELIVFAB.txt
C:\SHIPXML\XMLOut260FAB\ShipXMLOut260FAB.exe /log=verbose /db=PROD
copy C:\SHIPXML\XMLOut260FAB\XMLOUT\DOEFAB*.txt C:\SHIPXML\XMLOut260FAB\XMLOUT\NYCDELIVFAB.txt
copy C:\SHIPXML\XMLOut260FAB\XMLOUT\DOEFAB*.txt C:\SHIPXML\XMLOut260FAB\XMLOUTProcessed
rem FTP -s:C:\SHIPXML\XMLOut260FAB\DDPutXML.ftp >> DDPutXML.log
FTP -s:C:\SHIPXML\XMLOut260FAB\DDPutXML.ftp
DEL  C:\SHIPXML\XMLOut260FAB\XMLOUT\DOEFAB*.txt
DEL  C:\SHIPXML\XMLOut260FAB\XMLOUT\NYCDELIVFAB.txt
