//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UoCPOChgMapping.UCSDIPO {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UCSDIPOSOAP11Binding", Namespace="http://www.ibm.com/maximo/wsdl/UCSDIPO")]
    public partial class UCSDIPO : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback QueryUCSDIPOOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncUCSDIPOOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUCSDIPOOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateUCSDIPOOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUCSDIPOOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UCSDIPO() {
            this.Url = global::UoCPOChgMapping.Properties.Settings.Default.UoCPOChgMapping_UCSDIPO_UCSDIPO;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event QueryUCSDIPOCompletedEventHandler QueryUCSDIPOCompleted;
        
        /// <remarks/>
        public event SyncUCSDIPOCompletedEventHandler SyncUCSDIPOCompleted;
        
        /// <remarks/>
        public event UpdateUCSDIPOCompletedEventHandler UpdateUCSDIPOCompleted;
        
        /// <remarks/>
        public event CreateUCSDIPOCompletedEventHandler CreateUCSDIPOCompleted;
        
        /// <remarks/>
        public event DeleteUCSDIPOCompletedEventHandler DeleteUCSDIPOCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:processDocument", RequestNamespace="http://www.ibm.com/maximo", ResponseNamespace="http://www.ibm.com/maximo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("UCSDIPOSet")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("PO", IsNullable=false)]
        public UCSDIPO_POType[] QueryUCSDIPO(UCSDIPOQueryType UCSDIPOQuery, [System.Xml.Serialization.XmlAttributeAttribute()] ref System.DateTime creationDateTime, [System.Xml.Serialization.XmlAttributeAttribute()] [System.Xml.Serialization.XmlIgnoreAttribute()] ref bool creationDateTimeSpecified, [System.Xml.Serialization.XmlAttributeAttribute()] ref string baseLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string transLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string messageID, [System.Xml.Serialization.XmlAttributeAttribute()] ref string maximoVersion, [System.Xml.Serialization.XmlAttributeAttribute()] [System.ComponentModel.DefaultValueAttribute(false)] bool uniqueResult, [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")] string maxItems, [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")] [System.ComponentModel.DefaultValueAttribute("0")] ref string rsStart, [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")] out string rsCount, [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")] out string rsTotal) {
            object[] results = this.Invoke("QueryUCSDIPO", new object[] {
                        UCSDIPOQuery,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion,
                        uniqueResult,
                        maxItems,
                        rsStart});
            creationDateTime = ((System.DateTime)(results[1]));
            creationDateTimeSpecified = ((bool)(results[2]));
            baseLanguage = ((string)(results[3]));
            transLanguage = ((string)(results[4]));
            messageID = ((string)(results[5]));
            maximoVersion = ((string)(results[6]));
            rsStart = ((string)(results[7]));
            rsCount = ((string)(results[8]));
            rsTotal = ((string)(results[9]));
            return ((UCSDIPO_POType[])(results[0]));
        }
        
        /// <remarks/>
        public void QueryUCSDIPOAsync(UCSDIPOQueryType UCSDIPOQuery, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion, bool uniqueResult, string maxItems, string rsStart) {
            this.QueryUCSDIPOAsync(UCSDIPOQuery, creationDateTime, creationDateTimeSpecified, baseLanguage, transLanguage, messageID, maximoVersion, uniqueResult, maxItems, rsStart, null);
        }
        
        /// <remarks/>
        public void QueryUCSDIPOAsync(UCSDIPOQueryType UCSDIPOQuery, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion, bool uniqueResult, string maxItems, string rsStart, object userState) {
            if ((this.QueryUCSDIPOOperationCompleted == null)) {
                this.QueryUCSDIPOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryUCSDIPOOperationCompleted);
            }
            this.InvokeAsync("QueryUCSDIPO", new object[] {
                        UCSDIPOQuery,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion,
                        uniqueResult,
                        maxItems,
                        rsStart}, this.QueryUCSDIPOOperationCompleted, userState);
        }
        
        private void OnQueryUCSDIPOOperationCompleted(object arg) {
            if ((this.QueryUCSDIPOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryUCSDIPOCompleted(this, new QueryUCSDIPOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:processDocument", RequestNamespace="http://www.ibm.com/maximo", ResponseNamespace="http://www.ibm.com/maximo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SyncUCSDIPO([System.Xml.Serialization.XmlArrayItemAttribute("PO", IsNullable=false)] UCSDIPO_POType[] UCSDIPOSet, [System.Xml.Serialization.XmlAttributeAttribute()] ref System.DateTime creationDateTime, [System.Xml.Serialization.XmlAttributeAttribute()] [System.Xml.Serialization.XmlIgnoreAttribute()] ref bool creationDateTimeSpecified, [System.Xml.Serialization.XmlAttributeAttribute()] ref string baseLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string transLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string messageID, [System.Xml.Serialization.XmlAttributeAttribute()] ref string maximoVersion) {
            object[] results = this.Invoke("SyncUCSDIPO", new object[] {
                        UCSDIPOSet,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion});
            creationDateTime = ((System.DateTime)(results[0]));
            creationDateTimeSpecified = ((bool)(results[1]));
            baseLanguage = ((string)(results[2]));
            transLanguage = ((string)(results[3]));
            messageID = ((string)(results[4]));
            maximoVersion = ((string)(results[5]));
        }
        
        /// <remarks/>
        public void SyncUCSDIPOAsync(UCSDIPO_POType[] UCSDIPOSet, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion) {
            this.SyncUCSDIPOAsync(UCSDIPOSet, creationDateTime, creationDateTimeSpecified, baseLanguage, transLanguage, messageID, maximoVersion, null);
        }
        
        /// <remarks/>
        public void SyncUCSDIPOAsync(UCSDIPO_POType[] UCSDIPOSet, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion, object userState) {
            if ((this.SyncUCSDIPOOperationCompleted == null)) {
                this.SyncUCSDIPOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncUCSDIPOOperationCompleted);
            }
            this.InvokeAsync("SyncUCSDIPO", new object[] {
                        UCSDIPOSet,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion}, this.SyncUCSDIPOOperationCompleted, userState);
        }
        
        private void OnSyncUCSDIPOOperationCompleted(object arg) {
            if ((this.SyncUCSDIPOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncUCSDIPOCompleted(this, new SyncUCSDIPOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:processDocument", RequestNamespace="http://www.ibm.com/maximo", ResponseNamespace="http://www.ibm.com/maximo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateUCSDIPO([System.Xml.Serialization.XmlArrayItemAttribute("PO", IsNullable=false)] UCSDIPO_POType[] UCSDIPOSet, [System.Xml.Serialization.XmlAttributeAttribute()] ref System.DateTime creationDateTime, [System.Xml.Serialization.XmlAttributeAttribute()] [System.Xml.Serialization.XmlIgnoreAttribute()] ref bool creationDateTimeSpecified, [System.Xml.Serialization.XmlAttributeAttribute()] ref string baseLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string transLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string messageID, [System.Xml.Serialization.XmlAttributeAttribute()] ref string maximoVersion) {
            object[] results = this.Invoke("UpdateUCSDIPO", new object[] {
                        UCSDIPOSet,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion});
            creationDateTime = ((System.DateTime)(results[0]));
            creationDateTimeSpecified = ((bool)(results[1]));
            baseLanguage = ((string)(results[2]));
            transLanguage = ((string)(results[3]));
            messageID = ((string)(results[4]));
            maximoVersion = ((string)(results[5]));
        }
        
        /// <remarks/>
        public void UpdateUCSDIPOAsync(UCSDIPO_POType[] UCSDIPOSet, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion) {
            this.UpdateUCSDIPOAsync(UCSDIPOSet, creationDateTime, creationDateTimeSpecified, baseLanguage, transLanguage, messageID, maximoVersion, null);
        }
        
        /// <remarks/>
        public void UpdateUCSDIPOAsync(UCSDIPO_POType[] UCSDIPOSet, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion, object userState) {
            if ((this.UpdateUCSDIPOOperationCompleted == null)) {
                this.UpdateUCSDIPOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUCSDIPOOperationCompleted);
            }
            this.InvokeAsync("UpdateUCSDIPO", new object[] {
                        UCSDIPOSet,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion}, this.UpdateUCSDIPOOperationCompleted, userState);
        }
        
        private void OnUpdateUCSDIPOOperationCompleted(object arg) {
            if ((this.UpdateUCSDIPOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUCSDIPOCompleted(this, new UpdateUCSDIPOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:processDocument", RequestNamespace="http://www.ibm.com/maximo", ResponseNamespace="http://www.ibm.com/maximo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("POMboKeySet")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("PO", IsNullable=false)]
        public POKeyType[] CreateUCSDIPO([System.Xml.Serialization.XmlArrayItemAttribute("PO", IsNullable=false)] UCSDIPO_POType[] UCSDIPOSet, [System.Xml.Serialization.XmlAttributeAttribute()] ref System.DateTime creationDateTime, [System.Xml.Serialization.XmlAttributeAttribute()] [System.Xml.Serialization.XmlIgnoreAttribute()] ref bool creationDateTimeSpecified, [System.Xml.Serialization.XmlAttributeAttribute()] ref string baseLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string transLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string messageID, [System.Xml.Serialization.XmlAttributeAttribute()] ref string maximoVersion) {
            object[] results = this.Invoke("CreateUCSDIPO", new object[] {
                        UCSDIPOSet,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion});
            creationDateTime = ((System.DateTime)(results[1]));
            creationDateTimeSpecified = ((bool)(results[2]));
            baseLanguage = ((string)(results[3]));
            transLanguage = ((string)(results[4]));
            messageID = ((string)(results[5]));
            maximoVersion = ((string)(results[6]));
            return ((POKeyType[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateUCSDIPOAsync(UCSDIPO_POType[] UCSDIPOSet, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion) {
            this.CreateUCSDIPOAsync(UCSDIPOSet, creationDateTime, creationDateTimeSpecified, baseLanguage, transLanguage, messageID, maximoVersion, null);
        }
        
        /// <remarks/>
        public void CreateUCSDIPOAsync(UCSDIPO_POType[] UCSDIPOSet, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion, object userState) {
            if ((this.CreateUCSDIPOOperationCompleted == null)) {
                this.CreateUCSDIPOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUCSDIPOOperationCompleted);
            }
            this.InvokeAsync("CreateUCSDIPO", new object[] {
                        UCSDIPOSet,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion}, this.CreateUCSDIPOOperationCompleted, userState);
        }
        
        private void OnCreateUCSDIPOOperationCompleted(object arg) {
            if ((this.CreateUCSDIPOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateUCSDIPOCompleted(this, new CreateUCSDIPOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:processDocument", RequestNamespace="http://www.ibm.com/maximo", ResponseNamespace="http://www.ibm.com/maximo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteUCSDIPO([System.Xml.Serialization.XmlArrayItemAttribute("PO", IsNullable=false)] UCSDIPO_POType[] UCSDIPOSet, [System.Xml.Serialization.XmlAttributeAttribute()] ref System.DateTime creationDateTime, [System.Xml.Serialization.XmlAttributeAttribute()] [System.Xml.Serialization.XmlIgnoreAttribute()] ref bool creationDateTimeSpecified, [System.Xml.Serialization.XmlAttributeAttribute()] ref string baseLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string transLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string messageID, [System.Xml.Serialization.XmlAttributeAttribute()] ref string maximoVersion) {
            object[] results = this.Invoke("DeleteUCSDIPO", new object[] {
                        UCSDIPOSet,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion});
            creationDateTime = ((System.DateTime)(results[0]));
            creationDateTimeSpecified = ((bool)(results[1]));
            baseLanguage = ((string)(results[2]));
            transLanguage = ((string)(results[3]));
            messageID = ((string)(results[4]));
            maximoVersion = ((string)(results[5]));
        }
        
        /// <remarks/>
        public void DeleteUCSDIPOAsync(UCSDIPO_POType[] UCSDIPOSet, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion) {
            this.DeleteUCSDIPOAsync(UCSDIPOSet, creationDateTime, creationDateTimeSpecified, baseLanguage, transLanguage, messageID, maximoVersion, null);
        }
        
        /// <remarks/>
        public void DeleteUCSDIPOAsync(UCSDIPO_POType[] UCSDIPOSet, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion, object userState) {
            if ((this.DeleteUCSDIPOOperationCompleted == null)) {
                this.DeleteUCSDIPOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUCSDIPOOperationCompleted);
            }
            this.InvokeAsync("DeleteUCSDIPO", new object[] {
                        UCSDIPOSet,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion}, this.DeleteUCSDIPOOperationCompleted, userState);
        }
        
        private void OnDeleteUCSDIPOOperationCompleted(object arg) {
            if ((this.DeleteUCSDIPOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUCSDIPOCompleted(this, new DeleteUCSDIPOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class UCSDIPOQueryType {
        
        private string wHEREField;
        
        private UCSDIPOQueryTypePO poField;
        
        private string orderbyField;
        
        private OperandModeType operandModeField;
        
        public UCSDIPOQueryType() {
            this.operandModeField = OperandModeType.AND;
        }
        
        /// <remarks/>
        public string WHERE {
            get {
                return this.wHEREField;
            }
            set {
                this.wHEREField = value;
            }
        }
        
        /// <remarks/>
        public UCSDIPOQueryTypePO PO {
            get {
                return this.poField;
            }
            set {
                this.poField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string orderby {
            get {
                return this.orderbyField;
            }
            set {
                this.orderbyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(OperandModeType.AND)]
        public OperandModeType operandMode {
            get {
                return this.operandModeField;
            }
            set {
                this.operandModeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/maximo")]
    public partial class UCSDIPOQueryTypePO {
        
        private MXStringQueryType[] pONUMField;
        
        private MXLongQueryType[] rEVISIONNUMField;
        
        private MXStringQueryType[] sITEIDField;
        
        private MXBooleanQueryType[] uC_NOPACKSLIPField;
        
        private MXDateTimeQueryType[] vENDELIVERYDATEField;
        
        private UCSDIPOQueryTypePOPOLINE pOLINEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PONUM")]
        public MXStringQueryType[] PONUM {
            get {
                return this.pONUMField;
            }
            set {
                this.pONUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("REVISIONNUM", IsNullable=true)]
        public MXLongQueryType[] REVISIONNUM {
            get {
                return this.rEVISIONNUMField;
            }
            set {
                this.rEVISIONNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SITEID")]
        public MXStringQueryType[] SITEID {
            get {
                return this.sITEIDField;
            }
            set {
                this.sITEIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UC_NOPACKSLIP")]
        public MXBooleanQueryType[] UC_NOPACKSLIP {
            get {
                return this.uC_NOPACKSLIPField;
            }
            set {
                this.uC_NOPACKSLIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VENDELIVERYDATE", IsNullable=true)]
        public MXDateTimeQueryType[] VENDELIVERYDATE {
            get {
                return this.vENDELIVERYDATEField;
            }
            set {
                this.vENDELIVERYDATEField = value;
            }
        }
        
        /// <remarks/>
        public UCSDIPOQueryTypePOPOLINE POLINE {
            get {
                return this.pOLINEField;
            }
            set {
                this.pOLINEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class MXStringQueryType {
        
        private QueryOperatorType operatorField;
        
        private bool operatorFieldSpecified;
        
        private bool operandModeORField;
        
        private bool operandModeORFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryOperatorType @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool operandModeOR {
            get {
                return this.operandModeORField;
            }
            set {
                this.operandModeORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operandModeORSpecified {
            get {
                return this.operandModeORFieldSpecified;
            }
            set {
                this.operandModeORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public enum QueryOperatorType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("=")]
        Item,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("!=")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("<")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("<=")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(">")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(">=")]
        Item5,
        
        /// <remarks/>
        EW,
        
        /// <remarks/>
        SW,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class POKeyType {
        
        private MXStringType sITEIDField;
        
        private MXStringType pONUMField;
        
        private MXLongType rEVISIONNUMField;
        
        /// <remarks/>
        public MXStringType SITEID {
            get {
                return this.sITEIDField;
            }
            set {
                this.sITEIDField = value;
            }
        }
        
        /// <remarks/>
        public MXStringType PONUM {
            get {
                return this.pONUMField;
            }
            set {
                this.pONUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXLongType REVISIONNUM {
            get {
                return this.rEVISIONNUMField;
            }
            set {
                this.rEVISIONNUMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class MXStringType {
        
        private bool changedField;
        
        private bool changedFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class MXLongType {
        
        private bool changedField;
        
        private bool changedFieldSpecified;
        
        private long valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public long Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class UCSDIPO_POLINEType {
        
        private MXLongType pOLINENUMField;
        
        private MXDateTimeType vENDELIVERYDATEField;
        
        private ProcessingActionType actionField;
        
        private bool actionFieldSpecified;
        
        private string relationshipField;
        
        private string deleteForInsertField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXLongType POLINENUM {
            get {
                return this.pOLINENUMField;
            }
            set {
                this.pOLINENUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTimeType VENDELIVERYDATE {
            get {
                return this.vENDELIVERYDATEField;
            }
            set {
                this.vENDELIVERYDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProcessingActionType action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string deleteForInsert {
            get {
                return this.deleteForInsertField;
            }
            set {
                this.deleteForInsertField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class MXDateTimeType {
        
        private bool changedField;
        
        private bool changedFieldSpecified;
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public enum ProcessingActionType {
        
        /// <remarks/>
        Add,
        
        /// <remarks/>
        Change,
        
        /// <remarks/>
        Replace,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        AddChange,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class MXBooleanType {
        
        private bool changedField;
        
        private bool changedFieldSpecified;
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class UCSDIPO_POType {
        
        private string mAXINTERRORMSGField;
        
        private MXStringType pONUMField;
        
        private MXLongType rEVISIONNUMField;
        
        private MXStringType sITEIDField;
        
        private MXBooleanType uC_NOPACKSLIPField;
        
        private MXDateTimeType vENDELIVERYDATEField;
        
        private UCSDIPO_POLINEType[] pOLINEField;
        
        private ProcessingActionType actionField;
        
        private bool actionFieldSpecified;
        
        private string relationshipField;
        
        private string deleteForInsertField;
        
        private string transLanguageField;
        
        /// <remarks/>
        public string MAXINTERRORMSG {
            get {
                return this.mAXINTERRORMSGField;
            }
            set {
                this.mAXINTERRORMSGField = value;
            }
        }
        
        /// <remarks/>
        public MXStringType PONUM {
            get {
                return this.pONUMField;
            }
            set {
                this.pONUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXLongType REVISIONNUM {
            get {
                return this.rEVISIONNUMField;
            }
            set {
                this.rEVISIONNUMField = value;
            }
        }
        
        /// <remarks/>
        public MXStringType SITEID {
            get {
                return this.sITEIDField;
            }
            set {
                this.sITEIDField = value;
            }
        }
        
        /// <remarks/>
        public MXBooleanType UC_NOPACKSLIP {
            get {
                return this.uC_NOPACKSLIPField;
            }
            set {
                this.uC_NOPACKSLIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTimeType VENDELIVERYDATE {
            get {
                return this.vENDELIVERYDATEField;
            }
            set {
                this.vENDELIVERYDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POLINE")]
        public UCSDIPO_POLINEType[] POLINE {
            get {
                return this.pOLINEField;
            }
            set {
                this.pOLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProcessingActionType action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string deleteForInsert {
            get {
                return this.deleteForInsertField;
            }
            set {
                this.deleteForInsertField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transLanguage {
            get {
                return this.transLanguageField;
            }
            set {
                this.transLanguageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class MXDateTimeQueryType {
        
        private QueryOperatorType operatorField;
        
        private bool operatorFieldSpecified;
        
        private bool operandModeORField;
        
        private bool operandModeORFieldSpecified;
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryOperatorType @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool operandModeOR {
            get {
                return this.operandModeORField;
            }
            set {
                this.operandModeORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operandModeORSpecified {
            get {
                return this.operandModeORFieldSpecified;
            }
            set {
                this.operandModeORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class MXBooleanQueryType {
        
        private QueryOperatorType operatorField;
        
        private bool operatorFieldSpecified;
        
        private bool operandModeORField;
        
        private bool operandModeORFieldSpecified;
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryOperatorType @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool operandModeOR {
            get {
                return this.operandModeORField;
            }
            set {
                this.operandModeORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operandModeORSpecified {
            get {
                return this.operandModeORFieldSpecified;
            }
            set {
                this.operandModeORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class MXLongQueryType {
        
        private QueryOperatorType operatorField;
        
        private bool operatorFieldSpecified;
        
        private bool operandModeORField;
        
        private bool operandModeORFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryOperatorType @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool operandModeOR {
            get {
                return this.operandModeORField;
            }
            set {
                this.operandModeORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operandModeORSpecified {
            get {
                return this.operandModeORFieldSpecified;
            }
            set {
                this.operandModeORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/maximo")]
    public partial class UCSDIPOQueryTypePOPOLINE {
        
        private MXLongQueryType[] pOLINENUMField;
        
        private MXDateTimeQueryType[] vENDELIVERYDATEField;
        
        private bool filterField;
        
        private bool filterFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POLINENUM", IsNullable=true)]
        public MXLongQueryType[] POLINENUM {
            get {
                return this.pOLINENUMField;
            }
            set {
                this.pOLINENUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VENDELIVERYDATE", IsNullable=true)]
        public MXDateTimeQueryType[] VENDELIVERYDATE {
            get {
                return this.vENDELIVERYDATEField;
            }
            set {
                this.vENDELIVERYDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool filterSpecified {
            get {
                return this.filterFieldSpecified;
            }
            set {
                this.filterFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public enum OperandModeType {
        
        /// <remarks/>
        OR,
        
        /// <remarks/>
        AND,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void QueryUCSDIPOCompletedEventHandler(object sender, QueryUCSDIPOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryUCSDIPOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryUCSDIPOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UCSDIPO_POType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UCSDIPO_POType[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.DateTime creationDateTime {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public bool creationDateTimeSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string baseLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string transLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string messageID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string maximoVersion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
        
        /// <remarks/>
        public string rsStart {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[7]));
            }
        }
        
        /// <remarks/>
        public string rsCount {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[8]));
            }
        }
        
        /// <remarks/>
        public string rsTotal {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[9]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void SyncUCSDIPOCompletedEventHandler(object sender, SyncUCSDIPOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncUCSDIPOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncUCSDIPOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime creationDateTime {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool creationDateTimeSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string baseLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string transLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string messageID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string maximoVersion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void UpdateUCSDIPOCompletedEventHandler(object sender, UpdateUCSDIPOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUCSDIPOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUCSDIPOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime creationDateTime {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool creationDateTimeSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string baseLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string transLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string messageID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string maximoVersion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CreateUCSDIPOCompletedEventHandler(object sender, CreateUCSDIPOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateUCSDIPOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateUCSDIPOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public POKeyType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((POKeyType[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.DateTime creationDateTime {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public bool creationDateTimeSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string baseLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string transLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string messageID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string maximoVersion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void DeleteUCSDIPOCompletedEventHandler(object sender, DeleteUCSDIPOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUCSDIPOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUCSDIPOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime creationDateTime {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool creationDateTimeSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string baseLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string transLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string messageID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string maximoVersion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
}

#pragma warning restore 1591