SELECT 
  RCPT.CUST_ID
, RCPT.PLANT 
, RCPT.ISA_WORK_ORDER_NO 
, RCPT.ACTIVITY_ID 
, RCPT.INV_ITEM_ID 
, RCPT.RECEIVER_ID 
, RCPT.PO_ID 
, RCPT.REQ_ID 
, RCPT.VENDOR_ID 
, RCPT.ISA_CUST_BIN 
, RCPT.QTY 
, RCPT.PRICE_PO 
, RCPT.SERIAL_ID 
, RCPT.BUSINESS_UNIT_IN 
, RCPT.STORAGE_AREA 
, RCPT.STOR_LEVEL_1 
, RCPT.STOR_LEVEL_2 
, RCPT.STOR_LEVEL_3 
, RCPT.STOR_LEVEL_4 
, RCPT.PROCESS_FLAG 
, RCPT.ISA_EMPLID_30
FROM SYSADM.PS_ISA_MB_RECEIPT RCPT
WHERE RCPT.CUST_ID = '{0}'
  AND RCPT.PROCESS_FLAG IN ('N','E')
ORDER BY 
  RCPT.CUST_ID
, RCPT.PLANT 
, RCPT.REQ_ID 
, RCPT.ISA_WORK_ORDER_NO 
, RCPT.ACTIVITY_ID 
, RCPT.INV_ITEM_ID 
, RCPT.ISA_CUST_BIN 
