//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UoCMinMaxMapping.UCSDIINVENTORY {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UCSDIINVENTORYSOAP11Binding", Namespace="http://www.ibm.com/maximo/wsdl/UCSDIINVENTORY")]
    public partial class UCSDIINVENTORY : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback QueryUCSDIINVENTORYOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncUCSDIINVENTORYOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUCSDIINVENTORYOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateUCSDIINVENTORYOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUCSDIINVENTORYOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UCSDIINVENTORY() {
            this.Url = global::UoCMinMaxMapping.Properties.Settings.Default.UoCMinMaxMapping_UCSDIINVENTORY_UCSDIINVENTORY;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event QueryUCSDIINVENTORYCompletedEventHandler QueryUCSDIINVENTORYCompleted;
        
        /// <remarks/>
        public event SyncUCSDIINVENTORYCompletedEventHandler SyncUCSDIINVENTORYCompleted;
        
        /// <remarks/>
        public event UpdateUCSDIINVENTORYCompletedEventHandler UpdateUCSDIINVENTORYCompleted;
        
        /// <remarks/>
        public event CreateUCSDIINVENTORYCompletedEventHandler CreateUCSDIINVENTORYCompleted;
        
        /// <remarks/>
        public event DeleteUCSDIINVENTORYCompletedEventHandler DeleteUCSDIINVENTORYCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:processDocument", RequestNamespace="http://www.ibm.com/maximo", ResponseNamespace="http://www.ibm.com/maximo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("UCSDIINVENTORYSet")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("INVENTORY", IsNullable=false)]
        public UCSDIINVENTORY_INVENTORYType[] QueryUCSDIINVENTORY(UCSDIINVENTORYQueryType UCSDIINVENTORYQuery, [System.Xml.Serialization.XmlAttributeAttribute()] ref System.DateTime creationDateTime, [System.Xml.Serialization.XmlAttributeAttribute()] [System.Xml.Serialization.XmlIgnoreAttribute()] ref bool creationDateTimeSpecified, [System.Xml.Serialization.XmlAttributeAttribute()] ref string baseLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string transLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string messageID, [System.Xml.Serialization.XmlAttributeAttribute()] ref string maximoVersion, [System.Xml.Serialization.XmlAttributeAttribute()] [System.ComponentModel.DefaultValueAttribute(false)] bool uniqueResult, [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")] string maxItems, [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")] [System.ComponentModel.DefaultValueAttribute("0")] ref string rsStart, [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")] out string rsCount, [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")] out string rsTotal) {
            object[] results = this.Invoke("QueryUCSDIINVENTORY", new object[] {
                        UCSDIINVENTORYQuery,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion,
                        uniqueResult,
                        maxItems,
                        rsStart});
            creationDateTime = ((System.DateTime)(results[1]));
            creationDateTimeSpecified = ((bool)(results[2]));
            baseLanguage = ((string)(results[3]));
            transLanguage = ((string)(results[4]));
            messageID = ((string)(results[5]));
            maximoVersion = ((string)(results[6]));
            rsStart = ((string)(results[7]));
            rsCount = ((string)(results[8]));
            rsTotal = ((string)(results[9]));
            return ((UCSDIINVENTORY_INVENTORYType[])(results[0]));
        }
        
        /// <remarks/>
        public void QueryUCSDIINVENTORYAsync(UCSDIINVENTORYQueryType UCSDIINVENTORYQuery, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion, bool uniqueResult, string maxItems, string rsStart) {
            this.QueryUCSDIINVENTORYAsync(UCSDIINVENTORYQuery, creationDateTime, creationDateTimeSpecified, baseLanguage, transLanguage, messageID, maximoVersion, uniqueResult, maxItems, rsStart, null);
        }
        
        /// <remarks/>
        public void QueryUCSDIINVENTORYAsync(UCSDIINVENTORYQueryType UCSDIINVENTORYQuery, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion, bool uniqueResult, string maxItems, string rsStart, object userState) {
            if ((this.QueryUCSDIINVENTORYOperationCompleted == null)) {
                this.QueryUCSDIINVENTORYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryUCSDIINVENTORYOperationCompleted);
            }
            this.InvokeAsync("QueryUCSDIINVENTORY", new object[] {
                        UCSDIINVENTORYQuery,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion,
                        uniqueResult,
                        maxItems,
                        rsStart}, this.QueryUCSDIINVENTORYOperationCompleted, userState);
        }
        
        private void OnQueryUCSDIINVENTORYOperationCompleted(object arg) {
            if ((this.QueryUCSDIINVENTORYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryUCSDIINVENTORYCompleted(this, new QueryUCSDIINVENTORYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:processDocument", RequestNamespace="http://www.ibm.com/maximo", ResponseNamespace="http://www.ibm.com/maximo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SyncUCSDIINVENTORY([System.Xml.Serialization.XmlArrayItemAttribute("INVENTORY", IsNullable=false)] UCSDIINVENTORY_INVENTORYType[] UCSDIINVENTORYSet, [System.Xml.Serialization.XmlAttributeAttribute()] ref System.DateTime creationDateTime, [System.Xml.Serialization.XmlAttributeAttribute()] [System.Xml.Serialization.XmlIgnoreAttribute()] ref bool creationDateTimeSpecified, [System.Xml.Serialization.XmlAttributeAttribute()] ref string baseLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string transLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string messageID, [System.Xml.Serialization.XmlAttributeAttribute()] ref string maximoVersion) {
            object[] results = this.Invoke("SyncUCSDIINVENTORY", new object[] {
                        UCSDIINVENTORYSet,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion});
            creationDateTime = ((System.DateTime)(results[0]));
            creationDateTimeSpecified = ((bool)(results[1]));
            baseLanguage = ((string)(results[2]));
            transLanguage = ((string)(results[3]));
            messageID = ((string)(results[4]));
            maximoVersion = ((string)(results[5]));
        }
        
        /// <remarks/>
        public void SyncUCSDIINVENTORYAsync(UCSDIINVENTORY_INVENTORYType[] UCSDIINVENTORYSet, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion) {
            this.SyncUCSDIINVENTORYAsync(UCSDIINVENTORYSet, creationDateTime, creationDateTimeSpecified, baseLanguage, transLanguage, messageID, maximoVersion, null);
        }
        
        /// <remarks/>
        public void SyncUCSDIINVENTORYAsync(UCSDIINVENTORY_INVENTORYType[] UCSDIINVENTORYSet, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion, object userState) {
            if ((this.SyncUCSDIINVENTORYOperationCompleted == null)) {
                this.SyncUCSDIINVENTORYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncUCSDIINVENTORYOperationCompleted);
            }
            this.InvokeAsync("SyncUCSDIINVENTORY", new object[] {
                        UCSDIINVENTORYSet,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion}, this.SyncUCSDIINVENTORYOperationCompleted, userState);
        }
        
        private void OnSyncUCSDIINVENTORYOperationCompleted(object arg) {
            if ((this.SyncUCSDIINVENTORYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncUCSDIINVENTORYCompleted(this, new SyncUCSDIINVENTORYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:processDocument", RequestNamespace="http://www.ibm.com/maximo", ResponseNamespace="http://www.ibm.com/maximo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateUCSDIINVENTORY([System.Xml.Serialization.XmlArrayItemAttribute("INVENTORY", IsNullable=false)] UCSDIINVENTORY_INVENTORYType[] UCSDIINVENTORYSet, [System.Xml.Serialization.XmlAttributeAttribute()] ref System.DateTime creationDateTime, [System.Xml.Serialization.XmlAttributeAttribute()] [System.Xml.Serialization.XmlIgnoreAttribute()] ref bool creationDateTimeSpecified, [System.Xml.Serialization.XmlAttributeAttribute()] ref string baseLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string transLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string messageID, [System.Xml.Serialization.XmlAttributeAttribute()] ref string maximoVersion) {
            object[] results = this.Invoke("UpdateUCSDIINVENTORY", new object[] {
                        UCSDIINVENTORYSet,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion});
            creationDateTime = ((System.DateTime)(results[0]));
            creationDateTimeSpecified = ((bool)(results[1]));
            baseLanguage = ((string)(results[2]));
            transLanguage = ((string)(results[3]));
            messageID = ((string)(results[4]));
            maximoVersion = ((string)(results[5]));
        }
        
        /// <remarks/>
        public void UpdateUCSDIINVENTORYAsync(UCSDIINVENTORY_INVENTORYType[] UCSDIINVENTORYSet, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion) {
            this.UpdateUCSDIINVENTORYAsync(UCSDIINVENTORYSet, creationDateTime, creationDateTimeSpecified, baseLanguage, transLanguage, messageID, maximoVersion, null);
        }
        
        /// <remarks/>
        public void UpdateUCSDIINVENTORYAsync(UCSDIINVENTORY_INVENTORYType[] UCSDIINVENTORYSet, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion, object userState) {
            if ((this.UpdateUCSDIINVENTORYOperationCompleted == null)) {
                this.UpdateUCSDIINVENTORYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUCSDIINVENTORYOperationCompleted);
            }
            this.InvokeAsync("UpdateUCSDIINVENTORY", new object[] {
                        UCSDIINVENTORYSet,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion}, this.UpdateUCSDIINVENTORYOperationCompleted, userState);
        }
        
        private void OnUpdateUCSDIINVENTORYOperationCompleted(object arg) {
            if ((this.UpdateUCSDIINVENTORYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUCSDIINVENTORYCompleted(this, new UpdateUCSDIINVENTORYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:processDocument", RequestNamespace="http://www.ibm.com/maximo", ResponseNamespace="http://www.ibm.com/maximo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("INVENTORYMboKeySet")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("INVENTORY", IsNullable=false)]
        public INVENTORYKeyType[] CreateUCSDIINVENTORY([System.Xml.Serialization.XmlArrayItemAttribute("INVENTORY", IsNullable=false)] UCSDIINVENTORY_INVENTORYType[] UCSDIINVENTORYSet, [System.Xml.Serialization.XmlAttributeAttribute()] ref System.DateTime creationDateTime, [System.Xml.Serialization.XmlAttributeAttribute()] [System.Xml.Serialization.XmlIgnoreAttribute()] ref bool creationDateTimeSpecified, [System.Xml.Serialization.XmlAttributeAttribute()] ref string baseLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string transLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string messageID, [System.Xml.Serialization.XmlAttributeAttribute()] ref string maximoVersion) {
            object[] results = this.Invoke("CreateUCSDIINVENTORY", new object[] {
                        UCSDIINVENTORYSet,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion});
            creationDateTime = ((System.DateTime)(results[1]));
            creationDateTimeSpecified = ((bool)(results[2]));
            baseLanguage = ((string)(results[3]));
            transLanguage = ((string)(results[4]));
            messageID = ((string)(results[5]));
            maximoVersion = ((string)(results[6]));
            return ((INVENTORYKeyType[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateUCSDIINVENTORYAsync(UCSDIINVENTORY_INVENTORYType[] UCSDIINVENTORYSet, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion) {
            this.CreateUCSDIINVENTORYAsync(UCSDIINVENTORYSet, creationDateTime, creationDateTimeSpecified, baseLanguage, transLanguage, messageID, maximoVersion, null);
        }
        
        /// <remarks/>
        public void CreateUCSDIINVENTORYAsync(UCSDIINVENTORY_INVENTORYType[] UCSDIINVENTORYSet, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion, object userState) {
            if ((this.CreateUCSDIINVENTORYOperationCompleted == null)) {
                this.CreateUCSDIINVENTORYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUCSDIINVENTORYOperationCompleted);
            }
            this.InvokeAsync("CreateUCSDIINVENTORY", new object[] {
                        UCSDIINVENTORYSet,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion}, this.CreateUCSDIINVENTORYOperationCompleted, userState);
        }
        
        private void OnCreateUCSDIINVENTORYOperationCompleted(object arg) {
            if ((this.CreateUCSDIINVENTORYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateUCSDIINVENTORYCompleted(this, new CreateUCSDIINVENTORYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:processDocument", RequestNamespace="http://www.ibm.com/maximo", ResponseNamespace="http://www.ibm.com/maximo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteUCSDIINVENTORY([System.Xml.Serialization.XmlArrayItemAttribute("INVENTORY", IsNullable=false)] UCSDIINVENTORY_INVENTORYType[] UCSDIINVENTORYSet, [System.Xml.Serialization.XmlAttributeAttribute()] ref System.DateTime creationDateTime, [System.Xml.Serialization.XmlAttributeAttribute()] [System.Xml.Serialization.XmlIgnoreAttribute()] ref bool creationDateTimeSpecified, [System.Xml.Serialization.XmlAttributeAttribute()] ref string baseLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string transLanguage, [System.Xml.Serialization.XmlAttributeAttribute()] ref string messageID, [System.Xml.Serialization.XmlAttributeAttribute()] ref string maximoVersion) {
            object[] results = this.Invoke("DeleteUCSDIINVENTORY", new object[] {
                        UCSDIINVENTORYSet,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion});
            creationDateTime = ((System.DateTime)(results[0]));
            creationDateTimeSpecified = ((bool)(results[1]));
            baseLanguage = ((string)(results[2]));
            transLanguage = ((string)(results[3]));
            messageID = ((string)(results[4]));
            maximoVersion = ((string)(results[5]));
        }
        
        /// <remarks/>
        public void DeleteUCSDIINVENTORYAsync(UCSDIINVENTORY_INVENTORYType[] UCSDIINVENTORYSet, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion) {
            this.DeleteUCSDIINVENTORYAsync(UCSDIINVENTORYSet, creationDateTime, creationDateTimeSpecified, baseLanguage, transLanguage, messageID, maximoVersion, null);
        }
        
        /// <remarks/>
        public void DeleteUCSDIINVENTORYAsync(UCSDIINVENTORY_INVENTORYType[] UCSDIINVENTORYSet, System.DateTime creationDateTime, bool creationDateTimeSpecified, string baseLanguage, string transLanguage, string messageID, string maximoVersion, object userState) {
            if ((this.DeleteUCSDIINVENTORYOperationCompleted == null)) {
                this.DeleteUCSDIINVENTORYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUCSDIINVENTORYOperationCompleted);
            }
            this.InvokeAsync("DeleteUCSDIINVENTORY", new object[] {
                        UCSDIINVENTORYSet,
                        creationDateTime,
                        creationDateTimeSpecified,
                        baseLanguage,
                        transLanguage,
                        messageID,
                        maximoVersion}, this.DeleteUCSDIINVENTORYOperationCompleted, userState);
        }
        
        private void OnDeleteUCSDIINVENTORYOperationCompleted(object arg) {
            if ((this.DeleteUCSDIINVENTORYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUCSDIINVENTORYCompleted(this, new DeleteUCSDIINVENTORYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class UCSDIINVENTORYQueryType {
        
        private string wHEREField;
        
        private UCSDIINVENTORYQueryTypeINVENTORY iNVENTORYField;
        
        private string orderbyField;
        
        private OperandModeType operandModeField;
        
        public UCSDIINVENTORYQueryType() {
            this.operandModeField = OperandModeType.AND;
        }
        
        /// <remarks/>
        public string WHERE {
            get {
                return this.wHEREField;
            }
            set {
                this.wHEREField = value;
            }
        }
        
        /// <remarks/>
        public UCSDIINVENTORYQueryTypeINVENTORY INVENTORY {
            get {
                return this.iNVENTORYField;
            }
            set {
                this.iNVENTORYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string orderby {
            get {
                return this.orderbyField;
            }
            set {
                this.orderbyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(OperandModeType.AND)]
        public OperandModeType operandMode {
            get {
                return this.operandModeField;
            }
            set {
                this.operandModeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/maximo")]
    public partial class UCSDIINVENTORYQueryTypeINVENTORY {
        
        private MXStringQueryType[] iTEMNUMField;
        
        private MXStringQueryType[] iTEMSETIDField;
        
        private MXStringQueryType[] lOCATIONField;
        
        private MXDoubleQueryType[] mAXLEVELField;
        
        private MXDoubleQueryType[] mINLEVELField;
        
        private MXDoubleQueryType[] oRDERQTYField;
        
        private MXStringQueryType[] oRDERUNITField;
        
        private MXStringQueryType[] sITEIDField;
        
        private UCSDIINVENTORYQueryTypeINVENTORYINVCOST iNVCOSTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEMNUM")]
        public MXStringQueryType[] ITEMNUM {
            get {
                return this.iTEMNUMField;
            }
            set {
                this.iTEMNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEMSETID")]
        public MXStringQueryType[] ITEMSETID {
            get {
                return this.iTEMSETIDField;
            }
            set {
                this.iTEMSETIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LOCATION")]
        public MXStringQueryType[] LOCATION {
            get {
                return this.lOCATIONField;
            }
            set {
                this.lOCATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MAXLEVEL", IsNullable=true)]
        public MXDoubleQueryType[] MAXLEVEL {
            get {
                return this.mAXLEVELField;
            }
            set {
                this.mAXLEVELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MINLEVEL", IsNullable=true)]
        public MXDoubleQueryType[] MINLEVEL {
            get {
                return this.mINLEVELField;
            }
            set {
                this.mINLEVELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ORDERQTY", IsNullable=true)]
        public MXDoubleQueryType[] ORDERQTY {
            get {
                return this.oRDERQTYField;
            }
            set {
                this.oRDERQTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ORDERUNIT")]
        public MXStringQueryType[] ORDERUNIT {
            get {
                return this.oRDERUNITField;
            }
            set {
                this.oRDERUNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SITEID")]
        public MXStringQueryType[] SITEID {
            get {
                return this.sITEIDField;
            }
            set {
                this.sITEIDField = value;
            }
        }
        
        /// <remarks/>
        public UCSDIINVENTORYQueryTypeINVENTORYINVCOST INVCOST {
            get {
                return this.iNVCOSTField;
            }
            set {
                this.iNVCOSTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class MXStringQueryType {
        
        private QueryOperatorType operatorField;
        
        private bool operatorFieldSpecified;
        
        private bool operandModeORField;
        
        private bool operandModeORFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryOperatorType @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool operandModeOR {
            get {
                return this.operandModeORField;
            }
            set {
                this.operandModeORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operandModeORSpecified {
            get {
                return this.operandModeORFieldSpecified;
            }
            set {
                this.operandModeORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public enum QueryOperatorType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("=")]
        Item,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("!=")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("<")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("<=")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(">")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(">=")]
        Item5,
        
        /// <remarks/>
        EW,
        
        /// <remarks/>
        SW,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class INVENTORYKeyType {
        
        private MXStringType iTEMNUMField;
        
        private MXStringType lOCATIONField;
        
        private MXStringType sITEIDField;
        
        private MXStringType iTEMSETIDField;
        
        /// <remarks/>
        public MXStringType ITEMNUM {
            get {
                return this.iTEMNUMField;
            }
            set {
                this.iTEMNUMField = value;
            }
        }
        
        /// <remarks/>
        public MXStringType LOCATION {
            get {
                return this.lOCATIONField;
            }
            set {
                this.lOCATIONField = value;
            }
        }
        
        /// <remarks/>
        public MXStringType SITEID {
            get {
                return this.sITEIDField;
            }
            set {
                this.sITEIDField = value;
            }
        }
        
        /// <remarks/>
        public MXStringType ITEMSETID {
            get {
                return this.iTEMSETIDField;
            }
            set {
                this.iTEMSETIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class MXStringType {
        
        private bool changedField;
        
        private bool changedFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class UCSDIINVENTORY_INVCOSTType {
        
        private MXDoubleType aVGCOSTField;
        
        private MXStringType cONDITIONCODEField;
        
        private MXDoubleType nEWAVGCOSTField;
        
        private ProcessingActionType actionField;
        
        private bool actionFieldSpecified;
        
        private string relationshipField;
        
        private string deleteForInsertField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDoubleType AVGCOST {
            get {
                return this.aVGCOSTField;
            }
            set {
                this.aVGCOSTField = value;
            }
        }
        
        /// <remarks/>
        public MXStringType CONDITIONCODE {
            get {
                return this.cONDITIONCODEField;
            }
            set {
                this.cONDITIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDoubleType NEWAVGCOST {
            get {
                return this.nEWAVGCOSTField;
            }
            set {
                this.nEWAVGCOSTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProcessingActionType action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string deleteForInsert {
            get {
                return this.deleteForInsertField;
            }
            set {
                this.deleteForInsertField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class MXDoubleType {
        
        private bool changedField;
        
        private bool changedFieldSpecified;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public enum ProcessingActionType {
        
        /// <remarks/>
        Add,
        
        /// <remarks/>
        Change,
        
        /// <remarks/>
        Replace,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        AddChange,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class UCSDIINVENTORY_INVENTORYType {
        
        private string mAXINTERRORMSGField;
        
        private MXStringType iTEMNUMField;
        
        private MXStringType iTEMSETIDField;
        
        private MXStringType lOCATIONField;
        
        private MXDoubleType mAXLEVELField;
        
        private MXDoubleType mINLEVELField;
        
        private MXDoubleType oRDERQTYField;
        
        private MXStringType oRDERUNITField;
        
        private MXStringType sITEIDField;
        
        private UCSDIINVENTORY_INVCOSTType[] iNVCOSTField;
        
        private ProcessingActionType actionField;
        
        private bool actionFieldSpecified;
        
        private string relationshipField;
        
        private string deleteForInsertField;
        
        private string transLanguageField;
        
        /// <remarks/>
        public string MAXINTERRORMSG {
            get {
                return this.mAXINTERRORMSGField;
            }
            set {
                this.mAXINTERRORMSGField = value;
            }
        }
        
        /// <remarks/>
        public MXStringType ITEMNUM {
            get {
                return this.iTEMNUMField;
            }
            set {
                this.iTEMNUMField = value;
            }
        }
        
        /// <remarks/>
        public MXStringType ITEMSETID {
            get {
                return this.iTEMSETIDField;
            }
            set {
                this.iTEMSETIDField = value;
            }
        }
        
        /// <remarks/>
        public MXStringType LOCATION {
            get {
                return this.lOCATIONField;
            }
            set {
                this.lOCATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDoubleType MAXLEVEL {
            get {
                return this.mAXLEVELField;
            }
            set {
                this.mAXLEVELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDoubleType MINLEVEL {
            get {
                return this.mINLEVELField;
            }
            set {
                this.mINLEVELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDoubleType ORDERQTY {
            get {
                return this.oRDERQTYField;
            }
            set {
                this.oRDERQTYField = value;
            }
        }
        
        /// <remarks/>
        public MXStringType ORDERUNIT {
            get {
                return this.oRDERUNITField;
            }
            set {
                this.oRDERUNITField = value;
            }
        }
        
        /// <remarks/>
        public MXStringType SITEID {
            get {
                return this.sITEIDField;
            }
            set {
                this.sITEIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INVCOST")]
        public UCSDIINVENTORY_INVCOSTType[] INVCOST {
            get {
                return this.iNVCOSTField;
            }
            set {
                this.iNVCOSTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProcessingActionType action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string deleteForInsert {
            get {
                return this.deleteForInsertField;
            }
            set {
                this.deleteForInsertField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transLanguage {
            get {
                return this.transLanguageField;
            }
            set {
                this.transLanguageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public partial class MXDoubleQueryType {
        
        private QueryOperatorType operatorField;
        
        private bool operatorFieldSpecified;
        
        private bool operandModeORField;
        
        private bool operandModeORFieldSpecified;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryOperatorType @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool operandModeOR {
            get {
                return this.operandModeORField;
            }
            set {
                this.operandModeORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operandModeORSpecified {
            get {
                return this.operandModeORFieldSpecified;
            }
            set {
                this.operandModeORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/maximo")]
    public partial class UCSDIINVENTORYQueryTypeINVENTORYINVCOST {
        
        private MXDoubleQueryType[] aVGCOSTField;
        
        private MXStringQueryType[] cONDITIONCODEField;
        
        private bool filterField;
        
        private bool filterFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AVGCOST", IsNullable=true)]
        public MXDoubleQueryType[] AVGCOST {
            get {
                return this.aVGCOSTField;
            }
            set {
                this.aVGCOSTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CONDITIONCODE")]
        public MXStringQueryType[] CONDITIONCODE {
            get {
                return this.cONDITIONCODEField;
            }
            set {
                this.cONDITIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool filterSpecified {
            get {
                return this.filterFieldSpecified;
            }
            set {
                this.filterFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
    public enum OperandModeType {
        
        /// <remarks/>
        OR,
        
        /// <remarks/>
        AND,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void QueryUCSDIINVENTORYCompletedEventHandler(object sender, QueryUCSDIINVENTORYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryUCSDIINVENTORYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryUCSDIINVENTORYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UCSDIINVENTORY_INVENTORYType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UCSDIINVENTORY_INVENTORYType[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.DateTime creationDateTime {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public bool creationDateTimeSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string baseLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string transLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string messageID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string maximoVersion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
        
        /// <remarks/>
        public string rsStart {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[7]));
            }
        }
        
        /// <remarks/>
        public string rsCount {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[8]));
            }
        }
        
        /// <remarks/>
        public string rsTotal {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[9]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SyncUCSDIINVENTORYCompletedEventHandler(object sender, SyncUCSDIINVENTORYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncUCSDIINVENTORYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncUCSDIINVENTORYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime creationDateTime {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool creationDateTimeSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string baseLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string transLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string messageID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string maximoVersion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void UpdateUCSDIINVENTORYCompletedEventHandler(object sender, UpdateUCSDIINVENTORYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUCSDIINVENTORYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUCSDIINVENTORYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime creationDateTime {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool creationDateTimeSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string baseLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string transLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string messageID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string maximoVersion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CreateUCSDIINVENTORYCompletedEventHandler(object sender, CreateUCSDIINVENTORYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateUCSDIINVENTORYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateUCSDIINVENTORYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public INVENTORYKeyType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((INVENTORYKeyType[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.DateTime creationDateTime {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public bool creationDateTimeSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string baseLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string transLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string messageID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string maximoVersion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeleteUCSDIINVENTORYCompletedEventHandler(object sender, DeleteUCSDIINVENTORYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUCSDIINVENTORYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUCSDIINVENTORYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime creationDateTime {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool creationDateTimeSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string baseLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string transLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string messageID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string maximoVersion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
}

#pragma warning restore 1591