SELECT (B.ISA_APPROVAL_CD || '-' || B.ISA_DESC) as PDESC
FROM
 PS_ISA_PICKING_INT A
,PS_ISA_ORD_INTFC_M B
WHERE A.SOURCE_BUS_UNIT = ':KEY_SOURCE_BU'
 AND A.ORDER_NO = ':KEY_ORDER_NO'
 AND A.ORDER_NO = B.ORDER_NO
 AND A.INV_ITEM_ID = B.INV_ITEM_ID
 AND A.ORDER_INT_LINE_NO = B.LINE_NBR
 AND ROWNUM < 2