SELECT DISTINCT B.SHIP_CNTR_ID
FROM
 PS_ISA_PICKING_INT A
,PS_ISA_PICKING_CNT B
WHERE
      A.SOURCE_BUS_UNIT = ':KEY_SOURCE_BU'
  AND A.ORDER_NO = ':KEY_ORDER_NO'
  AND NOT A.ENDDTTM IS NULL
  AND A.QTY_PICKED > 0
  AND A.BUSINESS_UNIT = B.BUSINESS_UNIT
  AND A.DEMAND_SOURCE = B.DEMAND_SOURCE
  AND A.SOURCE_BUS_UNIT = B.SOURCE_BUS_UNIT
  AND A.ORDER_NO = B.ORDER_NO
  AND A.ORDER_INT_LINE_NO = B.ORDER_INT_LINE_NO
  AND A.SCHED_LINE_NO = B.SCHED_LINE_NO
  AND A.INV_ITEM_ID = B.INV_ITEM_ID
  AND A.DEMAND_LINE_NO = B.DEMAND_LINE_NO
  AND A.SEQ_NBR = B.SEQ_NBR
  AND A.RECEIVER_ID = B.RECEIVER_ID
  AND A.RECV_LN_NBR = B.RECV_LN_NBR