SELECT
 '*** INVENTORY TRANSFER ***' AS ISA_CUST_NOTES
,A.LOCATION AS SHIPTO_ID
,A.DESTIN_BU
FROM SYSADM.PS_MSR_HDR_INV A
WHERE A.BUSINESS_UNIT = ':KEY_SOURCE_BU'
  AND A.ORDER_NO = ':KEY_ORDER_NO'
  AND ROWNUM < 2
