SELECT *
FROM (
SELECT 
 A.ORDER_NO
,A.ORDER_INT_LINE_NO
,A.SCHED_LINE_NO
,A.INV_ITEM_ID
,B.SHIP_CNTR_ID
,A.ORDER_NO AS ISA_WORK_ORDER_NO
,(E.DESCR254 ||' MFG: '||M.MFG_ID||'/'||M.MFG_ITM_ID) as DESCR254
,TO_CHAR(A.ISA_PACK_DTTM,'YYYY-MM-DD') as pick_date
,(
  SELECT SUM(I.QTY_PICKED)
  FROM PS_ISA_PICKING_INT I
  WHERE I.ORDER_NO = A.ORDER_NO
    AND I.ORDER_INT_LINE_NO = A.ORDER_INT_LINE_NO
    AND I.INV_ITEM_ID = A.INV_ITEM_ID
 ) as QTY_PICKED
,A.DEMAND_SOURCE
,A.UNIT_MEASURE_PICK AS UNIT_OF_MEASURE
,A.QTY_PICKED_CONV AS QTY_ORDERED
,TO_CHAR(SYSDATE,'MM/DD/YY') as ORDER_DATE
,A.ASSIGNED_TO AS ISA_EMPLOYEE_ID
,'INVENTORY TRANSFER' AS ISA_EMPLOYEE_NAME
,A.SOURCE_BUS_UNIT
FROM
 PS_ISA_PICKING_CNT B
,PS_ISA_PICKING_INT A
,PS_INV_ITEMS E
,PS_ITEM_MFG M
WHERE
      A.SOURCE_BUS_UNIT = ':KEY_SOURCE_BU' 
  AND A.ORDER_NO = ':KEY_ORDER_NO' 
  AND A.BUSINESS_UNIT = B.BUSINESS_UNIT(+)
  AND A.DEMAND_SOURCE = B.DEMAND_SOURCE(+)
  AND A.SOURCE_BUS_UNIT = B.SOURCE_BUS_UNIT(+)
  AND A.ORDER_NO = B.ORDER_NO(+)
  AND A.ORDER_INT_LINE_NO = B.ORDER_INT_LINE_NO(+)
  AND A.SCHED_LINE_NO = B.SCHED_LINE_NO(+)
  AND A.INV_ITEM_ID = B.INV_ITEM_ID(+)
  AND A.DEMAND_LINE_NO = B.DEMAND_LINE_NO(+)
  AND A.SEQ_NBR = B.SEQ_NBR(+)
  AND A.RECEIVER_ID = B.RECEIVER_ID(+)
  AND A.RECV_LN_NBR = B.RECV_LN_NBR(+)
  AND NOT A.ENDDTTM IS NULL
  AND A.SHIP_DTTM IS NULL
  AND A.QTY_PICKED > 0
  AND A.INV_ITEM_ID = E.INV_ITEM_ID
  AND E.SETID = 'MAIN1'
  AND E.EFFDT = (
                 SELECT MAX(E_ED.EFFDT) 
                 FROM PS_INV_ITEMS E_ED
                 WHERE E.SETID = E_ED.SETID
                   AND E.INV_ITEM_ID = E_ED.INV_ITEM_ID
                   AND E_ED.EFFDT <= SYSDATE
                )
  AND E.SETID = M.SETID (+)
  AND E.INV_ITEM_ID = M.INV_ITEM_ID (+)
  AND M.PREFERRED_MFG (+) = 'Y'
GROUP BY 
 A.ORDER_NO
,A.ORDER_INT_LINE_NO
,A.SCHED_LINE_NO
,A.INV_ITEM_ID
,B.SHIP_CNTR_ID
,(E.DESCR254 ||' MFG: '||M.MFG_ID||'/'||M.MFG_ITM_ID)
,TO_CHAR(A.ISA_PACK_DTTM,'YYYY-MM-DD')
,A.DEMAND_SOURCE
,A.UNIT_MEASURE_PICK
,A.QTY_PICKED_CONV
,TO_CHAR(SYSDATE,'MM/DD/YY')
,A.ASSIGNED_TO
,A.SOURCE_BUS_UNIT
UNION ALL   
SELECT
 A.ORDER_NO
,A.ORDER_INT_LINE_NO
,A.SCHED_LINE_NO
,A.INV_ITEM_ID
,B.SHIP_CNTR_ID
,A.ORDER_NO AS ISA_WORK_ORDER_NO
,(E.DESCR254 ||' MFG: '||M.MFG_ID||'/'||M.MFG_ITM_ID) as DESCR254
,TO_CHAR(A.ISA_PACK_DTTM,'YYYY-MM-DD') as pick_date
,(
  SELECT SUM( I.QTY_PICKED)
  FROM PS_ISA_PICKING_INT I
  WHERE I.ORDER_NO = A.ORDER_NO
    AND I.ORDER_INT_LINE_NO = A.ORDER_INT_LINE_NO
    AND I.INV_ITEM_ID = A.INV_ITEM_ID
 ) as QTY_PICKED
,A.DEMAND_SOURCE
,A.UNIT_MEASURE_PICK AS UNIT_OF_MEASURE
,A.QTY_PICKED_CONV AS QTY_ORDERED
,TO_CHAR(SYSDATE,'MM/DD/YY') as ORDER_DATE
,A.ASSIGNED_TO AS ISA_EMPLOYEE_ID
,'INVENTORY TRANSFER' AS ISA_EMPLOYEE_NAME
,A.SOURCE_BUS_UNIT
FROM
 PS_ISA_PICKING_CNT B
,PS_ISA_PICKING_INT A
,PS_INV_ITEMS E
,PS_ITEM_MFG M   
WHERE
      A.SOURCE_BUS_UNIT = ':KEY_SOURCE_BU'
  AND A.ORDER_NO = ':KEY_ORDER_NO'
  AND A.BUSINESS_UNIT = B.BUSINESS_UNIT(+)
  AND A.DEMAND_SOURCE = B.DEMAND_SOURCE(+)
  AND A.SOURCE_BUS_UNIT = B.SOURCE_BUS_UNIT(+)
  AND A.ORDER_NO = B.ORDER_NO(+)
  AND A.ORDER_INT_LINE_NO = B.ORDER_INT_LINE_NO(+)
  AND A.SCHED_LINE_NO = B.SCHED_LINE_NO(+)
  AND A.INV_ITEM_ID = B.INV_ITEM_ID(+)
  AND A.DEMAND_LINE_NO = B.DEMAND_LINE_NO(+)
  AND A.SEQ_NBR = B.SEQ_NBR(+)
  AND A.RECEIVER_ID = B.RECEIVER_ID(+)
  AND A.RECV_LN_NBR = B.RECV_LN_NBR(+)
  AND NOT A.ENDDTTM IS NULL
  AND A.SHIP_DTTM IS NULL
  AND A.QTY_PICKED = 0
  AND (
       SELECT COUNT(1)
       FROM PS_ISA_PICKING_INT F
       WHERE A.ORDER_NO = F.ORDER_NO
         AND A.ORDER_INT_LINE_NO = F.ORDER_INT_LINE_NO
         AND A.SCHED_LINE_NO = F.SCHED_LINE_NO
      ) = 1
  AND A.INV_ITEM_ID = E.INV_ITEM_ID
  AND E.SETID = 'MAIN1'
  AND E.EFFDT = (
                 SELECT MAX(E_ED.EFFDT)
                 FROM PS_INV_ITEMS E_ED
                 WHERE E.SETID = E_ED.SETID
                   AND E.INV_ITEM_ID = E_ED.INV_ITEM_ID
                   AND E_ED.EFFDT <= SYSDATE
                )
  AND E.SETID = M.SETID (+)
  AND E.INV_ITEM_ID = M.INV_ITEM_ID (+)
  AND M.PREFERRED_MFG (+) = 'Y'
GROUP BY 
 A.ORDER_NO
,A.ORDER_INT_LINE_NO
,A.SCHED_LINE_NO
,A.INV_ITEM_ID
,B.SHIP_CNTR_ID
,(E.DESCR254 ||' MFG: '||M.MFG_ID||'/'||M.MFG_ITM_ID)
,TO_CHAR(A.ISA_PACK_DTTM,'YYYY-MM-DD')
,A.DEMAND_SOURCE
,A.UNIT_MEASURE_PICK
,A.QTY_PICKED_CONV
,TO_CHAR(SYSDATE,'MM/DD/YY')
,A.ASSIGNED_TO
,A.SOURCE_BUS_UNIT
     ) Z
ORDER BY Z.ORDER_INT_LINE_NO,  Z.SCHED_LINE_NO, Z.SHIP_CNTR_ID