SELECT 
  CYCCNT.CUST_ID
, CYCCNT.EVENT_ID
, CYCCNT.PLANT
, CYCCNT.INV_ITEM_ID
, CYCCNT.ISA_CUST_BIN
, CYCCNT.QTY
, CYCCNT.BUSINESS_UNIT_IN
, CYCCNT.STORAGE_AREA
, CYCCNT.STOR_LEVEL_1
, CYCCNT.STOR_LEVEL_2
, CYCCNT.STOR_LEVEL_3
, CYCCNT.STOR_LEVEL_4
, CYCCNT.PROCESS_FLAG
FROM SYSADM.PS_ISA_MB_CYCLCNT CYCCNT
WHERE CYCCNT.CUST_ID = '{0}'
  AND CYCCNT.PROCESS_FLAG IN ('N','E')
ORDER BY 
  CYCCNT.PLANT
, CYCCNT.EVENT_ID
, CYCCNT.INV_ITEM_ID
, CYCCNT.ISA_CUST_BIN
