//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NYFoodOrderingServiceAccess.SFOrdering {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SFWebServiceSoap", Namespace="http://www.opt-osfns.org/")]
    public partial class SFWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOrdersXMLTodayOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrdersXMLAllBorosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrdersXMLTodayFinalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrdersXMLAllBorosFinalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrdersXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrdersDateRangeXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBaseOrderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SFWebService() {
            this.Url = global::NYFoodOrderingServiceAccess.Properties.Settings.Default.NYFoodOrderingServiceAccess_SFOrdering_SFWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOrdersXMLTodayCompletedEventHandler GetOrdersXMLTodayCompleted;
        
        /// <remarks/>
        public event GetOrdersXMLAllBorosCompletedEventHandler GetOrdersXMLAllBorosCompleted;
        
        /// <remarks/>
        public event GetOrdersXMLTodayFinalCompletedEventHandler GetOrdersXMLTodayFinalCompleted;
        
        /// <remarks/>
        public event GetOrdersXMLAllBorosFinalCompletedEventHandler GetOrdersXMLAllBorosFinalCompleted;
        
        /// <remarks/>
        public event GetOrdersXMLCompletedEventHandler GetOrdersXMLCompleted;
        
        /// <remarks/>
        public event GetOrdersDateRangeXMLCompletedEventHandler GetOrdersDateRangeXMLCompleted;
        
        /// <remarks/>
        public event GetBaseOrderCompletedEventHandler GetBaseOrderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.opt-osfns.org/GetOrdersXMLToday", RequestNamespace="http://www.opt-osfns.org/", ResponseNamespace="http://www.opt-osfns.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetOrdersXMLToday(string vendorId, string pwd) {
            object[] results = this.Invoke("GetOrdersXMLToday", new object[] {
                        vendorId,
                        pwd});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrdersXMLTodayAsync(string vendorId, string pwd) {
            this.GetOrdersXMLTodayAsync(vendorId, pwd, null);
        }
        
        /// <remarks/>
        public void GetOrdersXMLTodayAsync(string vendorId, string pwd, object userState) {
            if ((this.GetOrdersXMLTodayOperationCompleted == null)) {
                this.GetOrdersXMLTodayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrdersXMLTodayOperationCompleted);
            }
            this.InvokeAsync("GetOrdersXMLToday", new object[] {
                        vendorId,
                        pwd}, this.GetOrdersXMLTodayOperationCompleted, userState);
        }
        
        private void OnGetOrdersXMLTodayOperationCompleted(object arg) {
            if ((this.GetOrdersXMLTodayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrdersXMLTodayCompleted(this, new GetOrdersXMLTodayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.opt-osfns.org/GetOrdersXMLAllBoros", RequestNamespace="http://www.opt-osfns.org/", ResponseNamespace="http://www.opt-osfns.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetOrdersXMLAllBoros(string vendorId, string pwd, string deliveryDate) {
            object[] results = this.Invoke("GetOrdersXMLAllBoros", new object[] {
                        vendorId,
                        pwd,
                        deliveryDate});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrdersXMLAllBorosAsync(string vendorId, string pwd, string deliveryDate) {
            this.GetOrdersXMLAllBorosAsync(vendorId, pwd, deliveryDate, null);
        }
        
        /// <remarks/>
        public void GetOrdersXMLAllBorosAsync(string vendorId, string pwd, string deliveryDate, object userState) {
            if ((this.GetOrdersXMLAllBorosOperationCompleted == null)) {
                this.GetOrdersXMLAllBorosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrdersXMLAllBorosOperationCompleted);
            }
            this.InvokeAsync("GetOrdersXMLAllBoros", new object[] {
                        vendorId,
                        pwd,
                        deliveryDate}, this.GetOrdersXMLAllBorosOperationCompleted, userState);
        }
        
        private void OnGetOrdersXMLAllBorosOperationCompleted(object arg) {
            if ((this.GetOrdersXMLAllBorosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrdersXMLAllBorosCompleted(this, new GetOrdersXMLAllBorosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.opt-osfns.org/GetOrdersXMLTodayFinal", RequestNamespace="http://www.opt-osfns.org/", ResponseNamespace="http://www.opt-osfns.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetOrdersXMLTodayFinal(string vendorId, string pwd) {
            object[] results = this.Invoke("GetOrdersXMLTodayFinal", new object[] {
                        vendorId,
                        pwd});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrdersXMLTodayFinalAsync(string vendorId, string pwd) {
            this.GetOrdersXMLTodayFinalAsync(vendorId, pwd, null);
        }
        
        /// <remarks/>
        public void GetOrdersXMLTodayFinalAsync(string vendorId, string pwd, object userState) {
            if ((this.GetOrdersXMLTodayFinalOperationCompleted == null)) {
                this.GetOrdersXMLTodayFinalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrdersXMLTodayFinalOperationCompleted);
            }
            this.InvokeAsync("GetOrdersXMLTodayFinal", new object[] {
                        vendorId,
                        pwd}, this.GetOrdersXMLTodayFinalOperationCompleted, userState);
        }
        
        private void OnGetOrdersXMLTodayFinalOperationCompleted(object arg) {
            if ((this.GetOrdersXMLTodayFinalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrdersXMLTodayFinalCompleted(this, new GetOrdersXMLTodayFinalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.opt-osfns.org/GetOrdersXMLAllBorosFinal", RequestNamespace="http://www.opt-osfns.org/", ResponseNamespace="http://www.opt-osfns.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetOrdersXMLAllBorosFinal(string vendorId, string pwd, string deliveryDate) {
            object[] results = this.Invoke("GetOrdersXMLAllBorosFinal", new object[] {
                        vendorId,
                        pwd,
                        deliveryDate});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrdersXMLAllBorosFinalAsync(string vendorId, string pwd, string deliveryDate) {
            this.GetOrdersXMLAllBorosFinalAsync(vendorId, pwd, deliveryDate, null);
        }
        
        /// <remarks/>
        public void GetOrdersXMLAllBorosFinalAsync(string vendorId, string pwd, string deliveryDate, object userState) {
            if ((this.GetOrdersXMLAllBorosFinalOperationCompleted == null)) {
                this.GetOrdersXMLAllBorosFinalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrdersXMLAllBorosFinalOperationCompleted);
            }
            this.InvokeAsync("GetOrdersXMLAllBorosFinal", new object[] {
                        vendorId,
                        pwd,
                        deliveryDate}, this.GetOrdersXMLAllBorosFinalOperationCompleted, userState);
        }
        
        private void OnGetOrdersXMLAllBorosFinalOperationCompleted(object arg) {
            if ((this.GetOrdersXMLAllBorosFinalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrdersXMLAllBorosFinalCompleted(this, new GetOrdersXMLAllBorosFinalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.opt-osfns.org/GetOrdersXML", RequestNamespace="http://www.opt-osfns.org/", ResponseNamespace="http://www.opt-osfns.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetOrdersXML(string vendorId, string pwd, string deliveryDate, string boro, bool finalDownload) {
            object[] results = this.Invoke("GetOrdersXML", new object[] {
                        vendorId,
                        pwd,
                        deliveryDate,
                        boro,
                        finalDownload});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrdersXMLAsync(string vendorId, string pwd, string deliveryDate, string boro, bool finalDownload) {
            this.GetOrdersXMLAsync(vendorId, pwd, deliveryDate, boro, finalDownload, null);
        }
        
        /// <remarks/>
        public void GetOrdersXMLAsync(string vendorId, string pwd, string deliveryDate, string boro, bool finalDownload, object userState) {
            if ((this.GetOrdersXMLOperationCompleted == null)) {
                this.GetOrdersXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrdersXMLOperationCompleted);
            }
            this.InvokeAsync("GetOrdersXML", new object[] {
                        vendorId,
                        pwd,
                        deliveryDate,
                        boro,
                        finalDownload}, this.GetOrdersXMLOperationCompleted, userState);
        }
        
        private void OnGetOrdersXMLOperationCompleted(object arg) {
            if ((this.GetOrdersXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrdersXMLCompleted(this, new GetOrdersXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.opt-osfns.org/GetOrdersDateRangeXML", RequestNamespace="http://www.opt-osfns.org/", ResponseNamespace="http://www.opt-osfns.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetOrdersDateRangeXML(string vendorId, string pwd, string startDate, string endDate, string boro) {
            object[] results = this.Invoke("GetOrdersDateRangeXML", new object[] {
                        vendorId,
                        pwd,
                        startDate,
                        endDate,
                        boro});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrdersDateRangeXMLAsync(string vendorId, string pwd, string startDate, string endDate, string boro) {
            this.GetOrdersDateRangeXMLAsync(vendorId, pwd, startDate, endDate, boro, null);
        }
        
        /// <remarks/>
        public void GetOrdersDateRangeXMLAsync(string vendorId, string pwd, string startDate, string endDate, string boro, object userState) {
            if ((this.GetOrdersDateRangeXMLOperationCompleted == null)) {
                this.GetOrdersDateRangeXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrdersDateRangeXMLOperationCompleted);
            }
            this.InvokeAsync("GetOrdersDateRangeXML", new object[] {
                        vendorId,
                        pwd,
                        startDate,
                        endDate,
                        boro}, this.GetOrdersDateRangeXMLOperationCompleted, userState);
        }
        
        private void OnGetOrdersDateRangeXMLOperationCompleted(object arg) {
            if ((this.GetOrdersDateRangeXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrdersDateRangeXMLCompleted(this, new GetOrdersDateRangeXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.opt-osfns.org/GetBaseOrder", RequestNamespace="http://www.opt-osfns.org/", ResponseNamespace="http://www.opt-osfns.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetBaseOrder(string vendorId, string pwd) {
            object[] results = this.Invoke("GetBaseOrder", new object[] {
                        vendorId,
                        pwd});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetBaseOrderAsync(string vendorId, string pwd) {
            this.GetBaseOrderAsync(vendorId, pwd, null);
        }
        
        /// <remarks/>
        public void GetBaseOrderAsync(string vendorId, string pwd, object userState) {
            if ((this.GetBaseOrderOperationCompleted == null)) {
                this.GetBaseOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBaseOrderOperationCompleted);
            }
            this.InvokeAsync("GetBaseOrder", new object[] {
                        vendorId,
                        pwd}, this.GetBaseOrderOperationCompleted, userState);
        }
        
        private void OnGetBaseOrderOperationCompleted(object arg) {
            if ((this.GetBaseOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBaseOrderCompleted(this, new GetBaseOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetOrdersXMLTodayCompletedEventHandler(object sender, GetOrdersXMLTodayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrdersXMLTodayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrdersXMLTodayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetOrdersXMLAllBorosCompletedEventHandler(object sender, GetOrdersXMLAllBorosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrdersXMLAllBorosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrdersXMLAllBorosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetOrdersXMLTodayFinalCompletedEventHandler(object sender, GetOrdersXMLTodayFinalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrdersXMLTodayFinalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrdersXMLTodayFinalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetOrdersXMLAllBorosFinalCompletedEventHandler(object sender, GetOrdersXMLAllBorosFinalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrdersXMLAllBorosFinalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrdersXMLAllBorosFinalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetOrdersXMLCompletedEventHandler(object sender, GetOrdersXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrdersXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrdersXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetOrdersDateRangeXMLCompletedEventHandler(object sender, GetOrdersDateRangeXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrdersDateRangeXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrdersDateRangeXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetBaseOrderCompletedEventHandler(object sender, GetBaseOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBaseOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBaseOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591