'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SDI.MOMBrandEAMParentApp.dll")>  _
        Public ReadOnly Property ParentApp() As String
            Get
                Return CType(Me("ParentApp"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SDI.MOMBrandEAMParentApp.MOMBrandEAMParentApp")>  _
        Public ReadOnly Property ParentAppClass() As String
            Get
                Return CType(Me("ParentAppClass"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public ReadOnly Property ISSRET_GetBatchSize() As String
            Get
                Return CType(Me("ISSRET_GetBatchSize"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public ReadOnly Property ISSRET_MaxReq() As String
            Get
                Return CType(Me("ISSRET_MaxReq"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MOMBrand_ISSRET_HTTP_SOAP_TableColMap.xml")>  _
        Public ReadOnly Property ISSRET_HTTP_SOAP_DataMap() As String
            Get
                Return CType(Me("ISSRET_HTTP_SOAP_DataMap"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ISSRET_HTTP_SOAP_SelectToSend.sql")>  _
        Public ReadOnly Property ISSRET_SelectToSend() As String
            Get
                Return CType(Me("ISSRET_SelectToSend"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CUST_ID,TRANS_CODE,ISA_WORK_ORDER_NO,ACTIVITY_ID,SERIAL_ID,PLANT,INV_ITEM_ID,ISA_"& _ 
            "CUST_BIN,QTY,BUSINESS_UNIT_IN,STORAGE_AREA,STOR_LEVEL_1,STOR_LEVEL_2,STOR_LEVEL_"& _ 
            "3,STOR_LEVEL_4,ISA_EMPLID_30")>  _
        Public ReadOnly Property ISSRET_UpdateKeyColumns() As String
            Get
                Return CType(Me("ISSRET_UpdateKeyColumns"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MOMBrand_ISSRET_HTTP_SOAP_Batch.xml")>  _
        Public ReadOnly Property ISSRET_HTTP_SOAP_Batch() As String
            Get
                Return CType(Me("ISSRET_HTTP_SOAP_Batch"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MOMBrand_ISSRET_HTTP_SOAP_Batch_Item.xml")>  _
        Public ReadOnly Property ISSRET_HTTP_SOAP_Batch_Item() As String
            Get
                Return CType(Me("ISSRET_HTTP_SOAP_Batch_Item"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ISSRET_HTTP_SOAP_UpdateFromResp.sql")>  _
        Public ReadOnly Property ISSRET_UpdateInputTable() As String
            Get
                Return CType(Me("ISSRET_UpdateInputTable"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ISS=Issue,RET=Return,RPR=RPR")>  _
        Public ReadOnly Property ISSRET_TransactionCodeXRef() As String
            Get
                Return CType(Me("ISSRET_TransactionCodeXRef"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FALSE")>  _
        Public ReadOnly Property ISSRET_ClearErrMsgOnSuccess() As String
            Get
                Return CType(Me("ISSRET_ClearErrMsgOnSuccess"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("[Tt]=[Pp][Rr][Oo][Cc]\s[Nn]=[0-9]{0,5}(-[A-Za-z0-9_]*)?\s[Cc]=[0-9]{0,5}")>  _
        Public ReadOnly Property ISSRET_CanParseErrMsgSignature() As String
            Get
                Return CType(Me("ISSRET_CanParseErrMsgSignature"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\s[Nn]=[0-9]{0,5}(-[A-Za-z0-9_]*)?\s")>  _
        Public ReadOnly Property ISSRET_ErrMsgId() As String
            Get
                Return CType(Me("ISSRET_ErrMsgId"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ISSRET_HTTP_SOAP_GetErrMsgDesc.sql")>  _
        Public ReadOnly Property ISSRET_GetErrMsgDesc() As String
            Get
                Return CType(Me("ISSRET_GetErrMsgDesc"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SDI.ISSRET_HTTP_SOAP.My.MySettings
            Get
                Return Global.SDI.ISSRET_HTTP_SOAP.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
