'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace SDI_ISA_RECEIPT
    
    'CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2002/12/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ISA_RECEIPT_Binding", [Namespace]:="http://xmlns.oracle.com/Enterprise/ERP/services/ISA_RECEIPT.1")>  _
    Partial Public Class ISA_RECEIPT
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CallISA_RECEIPTOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ShipNoticeAmazon.My.MySettings.Default.ShipNoticeAmazon_SDI_ISA_RECEIPT_ISA_RECEIPT
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CallISA_RECEIPTCompleted As CallISA_RECEIPTCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ISA_RECEIPT.v1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function CallISA_RECEIPT(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://xmlns.oracle.com/Enterprise/Tools/schemas/ISA_RECEIPT.ISA_PORCH_SDIEX.V1")> ByVal ISA_PORCH_SDIEX As ISA_PORCH_SDIEX_TypeShape) As <System.Xml.Serialization.XmlElementAttribute("ISA_RCV_EX_RSP", [Namespace]:="http://xmlns.oracle.com/Enterprise/Tools/schemas/ISA_RECEIPT_SDI_EXCHANGE.ISA_RCV"& _ 
            "_EX_RSP.V1")> ISA_RCV_EX_RSP_TypeShape
            Dim results() As Object = Me.Invoke("CallISA_RECEIPT", New Object() {ISA_PORCH_SDIEX})
            Return CType(results(0),ISA_RCV_EX_RSP_TypeShape)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CallISA_RECEIPTAsync(ByVal ISA_PORCH_SDIEX As ISA_PORCH_SDIEX_TypeShape)
            Me.CallISA_RECEIPTAsync(ISA_PORCH_SDIEX, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CallISA_RECEIPTAsync(ByVal ISA_PORCH_SDIEX As ISA_PORCH_SDIEX_TypeShape, ByVal userState As Object)
            If (Me.CallISA_RECEIPTOperationCompleted Is Nothing) Then
                Me.CallISA_RECEIPTOperationCompleted = AddressOf Me.OnCallISA_RECEIPTOperationCompleted
            End If
            Me.InvokeAsync("CallISA_RECEIPT", New Object() {ISA_PORCH_SDIEX}, Me.CallISA_RECEIPTOperationCompleted, userState)
        End Sub
        
        Private Sub OnCallISA_RECEIPTOperationCompleted(ByVal arg As Object)
            If (Not (Me.CallISA_RECEIPTCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CallISA_RECEIPTCompleted(Me, New CallISA_RECEIPTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.oracle.com/Enterprise/Tools/schemas/ISA_RECEIPT.ISA_PORCH_SDIEX.V1")>  _
    Partial Public Class ISA_PORCH_SDIEX_TypeShape
        
        Private bUSINESS_UNIT_POField As String
        
        Private pO_IDField As String
        
        Private bUSINESS_UNIT_RECVField As String
        
        Private tRANSACTION_IDField As String
        
        Private iSA_PORCL_SDIEXField() As ISA_PORCL_SDIEX_TypeShape
        
        '''<remarks/>
        Public Property BUSINESS_UNIT_PO() As String
            Get
                Return Me.bUSINESS_UNIT_POField
            End Get
            Set
                Me.bUSINESS_UNIT_POField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PO_ID() As String
            Get
                Return Me.pO_IDField
            End Get
            Set
                Me.pO_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BUSINESS_UNIT_RECV() As String
            Get
                Return Me.bUSINESS_UNIT_RECVField
            End Get
            Set
                Me.bUSINESS_UNIT_RECVField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TRANSACTION_ID() As String
            Get
                Return Me.tRANSACTION_IDField
            End Get
            Set
                Me.tRANSACTION_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ISA_PORCL_SDIEX", [Namespace]:="http://xmlns.oracle.com/Enterprise/Tools/schemas/ISA_RECEIPT.ISA_PORCL_SDIEX.V1")>  _
        Public Property ISA_PORCL_SDIEX() As ISA_PORCL_SDIEX_TypeShape()
            Get
                Return Me.iSA_PORCL_SDIEXField
            End Get
            Set
                Me.iSA_PORCL_SDIEXField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.oracle.com/Enterprise/Tools/schemas/ISA_RECEIPT.ISA_PORCL_SDIEX.V1")>  _
    Partial Public Class ISA_PORCL_SDIEX_TypeShape
        
        Private bUSINESS_UNIT_POField As String
        
        Private pO_IDField As String
        
        Private lINE_NBRField As String
        
        Private bUSINESS_UNIT_RECVField As String
        
        Private qTY_POField As Decimal
        
        Private cB_SELECT_POField As String
        
        Private tRANSACTION_IDField As String
        
        Private rECEIVER_IDField As String
        
        '''<remarks/>
        Public Property BUSINESS_UNIT_PO() As String
            Get
                Return Me.bUSINESS_UNIT_POField
            End Get
            Set
                Me.bUSINESS_UNIT_POField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PO_ID() As String
            Get
                Return Me.pO_IDField
            End Get
            Set
                Me.pO_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property LINE_NBR() As String
            Get
                Return Me.lINE_NBRField
            End Get
            Set
                Me.lINE_NBRField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BUSINESS_UNIT_RECV() As String
            Get
                Return Me.bUSINESS_UNIT_RECVField
            End Get
            Set
                Me.bUSINESS_UNIT_RECVField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property QTY_PO() As Decimal
            Get
                Return Me.qTY_POField
            End Get
            Set
                Me.qTY_POField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CB_SELECT_PO() As String
            Get
                Return Me.cB_SELECT_POField
            End Get
            Set
                Me.cB_SELECT_POField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TRANSACTION_ID() As String
            Get
                Return Me.tRANSACTION_IDField
            End Get
            Set
                Me.tRANSACTION_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RECEIVER_ID() As String
            Get
                Return Me.rECEIVER_IDField
            End Get
            Set
                Me.rECEIVER_IDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://xmlns.oracle.com/Enterprise/Tools/schemas/ISA_RECEIPT_SDI_EXCHANGE.ISA_RCV"& _ 
        "_EX_RSP.V1")>  _
    Partial Public Class ISA_RCV_EX_RSP_TypeShape
        
        Private businessUnitRecvField As String
        
        Private transactionIdField As String
        
        Private receiverIdField As String
        
        Private seqNoField As String
        
        Private messageNbrField As String
        
        Private returnCodeField As String
        
        Private messageSeqField As String
        
        Private messageTextField As String
        
        '''<remarks/>
        Public Property businessUnitRecv() As String
            Get
                Return Me.businessUnitRecvField
            End Get
            Set
                Me.businessUnitRecvField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property transactionId() As String
            Get
                Return Me.transactionIdField
            End Get
            Set
                Me.transactionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property receiverId() As String
            Get
                Return Me.receiverIdField
            End Get
            Set
                Me.receiverIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property seqNo() As String
            Get
                Return Me.seqNoField
            End Get
            Set
                Me.seqNoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property messageNbr() As String
            Get
                Return Me.messageNbrField
            End Get
            Set
                Me.messageNbrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property returnCode() As String
            Get
                Return Me.returnCodeField
            End Get
            Set
                Me.returnCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property messageSeq() As String
            Get
                Return Me.messageSeqField
            End Get
            Set
                Me.messageSeqField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property messageText() As String
            Get
                Return Me.messageTextField
            End Get
            Set
                Me.messageTextField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")>  _
    Public Delegate Sub CallISA_RECEIPTCompletedEventHandler(ByVal sender As Object, ByVal e As CallISA_RECEIPTCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CallISA_RECEIPTCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ISA_RCV_EX_RSP_TypeShape
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ISA_RCV_EX_RSP_TypeShape)
            End Get
        End Property
    End Class
End Namespace
