#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SDiMobile.Droid.Resource", IsApplication=true)]

namespace SDiMobile.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Worklight.Xamarin.Android.Resource.String.library_name = global::SDiMobile.Droid.Resource.String.library_name;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::SDiMobile.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::SDiMobile.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int my_header = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int my_headertext = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int my_statusbar = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int my_text = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AppIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bin = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int home = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int key_2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int list = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int locked = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int locked1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int menu = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int noimage_new = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int refresh = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int SDiHeader = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int SDiLogo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sdim_icon_2 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int sdim_logo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int search = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int search1 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int shopcart = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int shopcart1 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int tick = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int tray = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int unlocked = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int user_4 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int user_4_1 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int users = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int library_name = 2130903042;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int ActionBar = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int TitleTextStyle = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
