SELECT 
  A.CUST_ID
, A.PLANT
, A.INV_ITEM_ID
, A.ISA_CUST_BIN
, A.QTY
, A.BUSINESS_UNIT_IN
, A.STORAGE_AREA
, A.STOR_LEVEL_1
, A.STOR_LEVEL_2
, A.STOR_LEVEL_3
, A.STOR_LEVEL_4
, A.PROCESS_FLAG
FROM SYSADM.PS_ISA_MB_ADJ A
WHERE A.CUST_ID = '{0}'
  AND A.PROCESS_FLAG IN ('N','E')
ORDER BY 
  A.CUST_ID
, A.PLANT
, A.INV_ITEM_ID
, A.ISA_CUST_BIN
, A.QTY DESC
