'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2463
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2463.
'
Namespace loadbalance
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SDI_loadbalance_IOSoap", [Namespace]:="http://www.Insiteonline.com")>  _
    Public Class SDI_loadbalance_IO
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://dazzle/SDI_loadbalance_IO/SDI_loadbalance_IO.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Insiteonline.com/Stat_Change_Email_Copy", RequestNamespace:="http://www.Insiteonline.com", ResponseNamespace:="http://www.Insiteonline.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Stat_Change_Email_Copy(ByVal filepath As String, ByVal StrMessage As String) As String
            Dim results() As Object = Me.Invoke("Stat_Change_Email_Copy", New Object() {filepath, StrMessage})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginStat_Change_Email_Copy(ByVal filepath As String, ByVal StrMessage As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Stat_Change_Email_Copy", New Object() {filepath, StrMessage}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndStat_Change_Email_Copy(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Insiteonline.com/Stat_Change_Email_Send", RequestNamespace:="http://www.Insiteonline.com", ResponseNamespace:="http://www.Insiteonline.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Stat_Change_Email_Send(ByVal filepath As String) As String
            Dim results() As Object = Me.Invoke("Stat_Change_Email_Send", New Object() {filepath})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginStat_Change_Email_Send(ByVal filepath As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Stat_Change_Email_Send", New Object() {filepath}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndStat_Change_Email_Send(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Insiteonline.com/Stat_Change_Email_check_dir_exist", RequestNamespace:="http://www.Insiteonline.com", ResponseNamespace:="http://www.Insiteonline.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Stat_Change_Email_check_dir_exist(ByVal rootdir As String) As String
            Dim results() As Object = Me.Invoke("Stat_Change_Email_check_dir_exist", New Object() {rootdir})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginStat_Change_Email_check_dir_exist(ByVal rootdir As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Stat_Change_Email_check_dir_exist", New Object() {rootdir}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndStat_Change_Email_check_dir_exist(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
